### ISSUE TITLE
LAN multiplayer doesn't work

### ISSUE THREAD

**Issue by NicknineTheEagle** [melonDS-emu/melonDS#1008]
I have two instances of melonDS running in the same local network on different machines and no matter what I try, they don't see each other in PicToChat and Download Play in Sonic Rush. Tested both slirp and pcap on both machines, neither work. melonDS is unblocked in firewall settings.

**Comment by WaluigiWare64** [comment]
Slirp and PCap are for playing over wifi, not local multiplayer.
Have you enabled bind socket to any address?

**Comment by NicknineTheEagle** [comment]
Uhm, pcap doesn't even work with wifi interfaces. I think you misunderstood me, I'm trying to use the feature where you can play wifi multiplayer over LAN.
Yes, I have that option enabled.

**Comment by WaluigiWare64** [comment]
PCap and Slirp are for playing over wifi, so connecting with another DS over Nintendo WFC (now shutdown, you can use alternatives such as Wiimmfi).

However, local multiplayer is where two DS systems are physically close to each other.

You seem to be talking about local multiplayer, as that is how Pictochat and Download Play work.

**Comment by NicknineTheEagle** [comment]
> PCap and Slirp are for playing over wifi, so connecting with another DS over Nintendo WFC (now shutdown, you can use alternatives such as Wiimmfi).
However, local multiplayer is where two DS systems are physically close to each other.

Ah, you should just have called it Nintendo WFC right off the bat, calling one "wifi" and the other "local multiplayer" is confusing as both use wireless connection in some way.

> Try disabling Frame Limiter and Audio Sync.

I have Frame Limiter disabled, I'll try turning off Audio Sync, too.

**Comment by NicknineTheEagle** [comment]
> Try disabling Frame Limiter and Audio Sync.

No dice, melonDS instances still don't see each other. This also makes emulated DS run at turbo speed.

**Comment by poudink** [comment]
enable mac randomization.

**Comment by NicknineTheEagle** [comment]
> 
> 
> enable mac randomization.

Now I have a peculiar situation where in PicToChat room list A sees B but B doesn't see A. If I enter the same room on both instances, they don't see each other and don't receive each other's messages.

**Comment by StLouisCPhT** [comment]
I tested this earlier today with the following results:
1) Running two copies of melonDS on the same Windows 10 PC works for Download Play.
2) Running one copy of melonDS on a M1 MacBook Pro and one copy on a Windows 10 PC works for Download Play
3) Running two copies of melonDS on the same M1 MacBook Pro does not work

In all 3 test cases the following settings were used:

1) Bind socket to any address
2) Randomize MAC address
3) Indirect Mode (uses libslirp,recommended)

I used the latest Windows x64 build available on the main page and the macOS version was build from the most recent source code on GitHub.

**Comment by dekefake** [comment]
I can confirm multiplayer isnt working properly with 2 instances of melonDS running on a M1 Mac, despite trying to enable/disable Audio Sync, Framerate Limiter, Mac randomization, Socket to all adresses, or direct/indirect mode.

1 instance on the M1 mac, and 1 on an Android phone are able to see each other with lost packets trough
