### ISSUE TITLE
about local  connections

### ISSUE THREAD

**Issue by ashgx** [melonDS-emu/melonDS#1046]
![QQ图片20210331091200](https://user-images.githubusercontent.com/81661156/113078222-3cf34600-9205-11eb-8a87-a74494b749e6.png)
I didn't know how to send this picture in the forum, so I sent it here.
When I tested, I turned on the randomized MAC address and JIT, and did not turn on the frame limit and audio sync in version 0.9.1. In the same way, Pokemon diamonds and pearls, Pokemon heart gold and soul silver can be connected locally. However, Pokemon black and white can't use a local connection.

**Comment by mwnDK1402** [comment]
I got to work in Pokémon Platinum by disabling Audio Sync, like you said. I hope it'll be possible to do it without these settings in the future, because the game runs at 200 FPS when I do it like that.

**Comment by MandL27** [comment]
Tested this in Namco Museum DS and had to disable audio sync on client instances as well. Framerate became more stable during gameplay, but in menus the clients were going much much faster.

As an aside, not sure if this is the game's fault or Melon's fault, but I consistently got desyncs when trying to emulate a four-player group. Two and three worked just fine, but with four players, two random client instances would always drop out after closing the room.

**Comment by RSDuck** [comment]
local wireless emulation is highly dependant on the OS scheduler (read: the coincidence that the OS runs all melonDS instances in roughly equal steps).

In the future we want to implement some way that the melonDS instances are manually synced up.

**Comment by KostaSaizo7** [comment]
> local wireless emulation is highly dependant on the OS scheduler (read: the coincidence that the OS runs all melonDS instances in roughly equal steps).
> 
> In the future we want to implement some way that the melonDS instances are manually synced up.

I think No$GBA emulates 2 DSes on the same instance. Can this be a potential solution?
![image](https://user-images.githubusercontent.com/39852873/116287405-09babd00-a799-11eb-92ce-6931af566830.png)

**Comment by RSDuck** [comment]
> I think No$GBA emulates 2 DSes on the same instance. Can this be a potential solution?

how so? no$gba is no$gba, melonDS is melonDS.

**Comment by KostaSaizo7** [comment]
> how so? no$gba is no$gba, melonDS is melonDS.

Right now, in order to do local multiplayer, we open 2 melonDS instances that communicate with each other. If I got your comment right, the OS doesn't sync the 2 instances correctly, hence the connection errors. But if MelonDS can emulate 2 DS consoles in the same instance, won't that eliminate the OS messing with the timings?

**Comment by RSDuck** [comment]
ah well I thought this was already mentioned in this thread. Getting two or more melonDS instances to run in the same process would require very significant changes to the structure of the code. Syncing two instances externaly would require significantly less effort.

**Comment by KostaSaizo7** [comment]
Fixed by https://github.com/melonDS-emu/melonDS/pull/1516
![Screenshot 2022-09-24 093527](https://user-images.githubusercontent.com/39852873/192083745-039e0226-75ea-4c78-99d4-ad296f6b5c2e.jpg)
![Screenshot 2022-09-24 093626](https://user-images.githubusercontent.com/39852873/192083754-e44ecbb9-3f2c-4109-83de-c5f060d4495b.jpg)
