### ISSUE TITLE
Improve Local Multiplayer

### ISSUE THREAD

**Issue by leeflix** [melonDS-emu/melonDS#1059]
First of all thanks for this amazing project!

I would love to play New Super Mario Bros. Versus (Local Multiplayer) with my friends to experience childhood memories anew. I tried many different settings but sadly it crashes alot which kills the fun. I don't think it is related to my CPU (i7-8700k).

As soon as Local Multiplayer is stable (at least for New Super Mario Bros.) I plan to implement a small application that mirrors the screen of one Melon instance to someone else over the internet and transfer their input to the corresponding Emulator to enable New Super Mario Bros. Versus Online Multiplayer. 😄

**Comment by Arisotura** [comment]
we're working on it!
