### ISSUE TITLE
Overflow calculation for SBC/RSC could be off

### ISSUE THREAD

**Issue by fleroviux** [melonDS-emu/melonDS#107]
Hi,

I think the way you calculate the V-flag for mentioned instructions might be off. I'm not sure if there are any differences between ARMv4 and ARMv5 (not that I would be aware of any, so I don't think so) so take this with a grain of salt.

**SBC/RSC connection of the two overflow bits**

Currently melonDS is connecting the overflow bits with an OR connector  however I'm pretty sure it should be **X**OR because if both subtractors sign-overflow **twice**  the final result doesn't have the sign bit flipped (well x *-1 * -1 = x).

I can't test this on the real thing unfortunaly but implementing it this way in NanoboyAdvance fixed the carry tests in the GBA test suite (by endrift) for me. Doing it with OR or any other kind of connection did not fix it. 

So yeah I hope this is helpful and I'm not a huge idiot with my reasoning lolz

Greetz,
flerovium

**Comment by StapleButter** [comment]
well, I'll try this, might fix some of the issues I observed

**Comment by StapleButter** [comment]
it didn't fix the particular issues I had in mind, but those seem to be timing issues.

I have a hard time thinking of a case where this would make a difference, tbh. I have to experiment with it I guess.

**Comment by RSDuck** [comment]
they should be corrected now.

The overflow flag for ADC, SBC and RSC is now calculated like described in the manual (only using 64-bit arithmetic instead of infinite precision, though it should never overflow).

See #1596
