### ISSUE TITLE
Add more CLI options

### ISSUE THREAD

**Issue by rzumer** [melonDS-emu/melonDS#1108]
Requests for additional command line flags/options to override default configuration parameters are pretty common, but there was no existing GitHub issue for it, so here's one.

**Comment by bg2908** [comment]
Right now, I can't open ROM inside archive from lutris. A argument to do that would help me save some space from the ROM.

**Comment by itsonlyMiRE** [comment]
leaving a comment as a +1/bump, because of course that will motivate the devs to prioritize CLI stuff :)

**Comment by vgambier** [comment]
Being able to specify NDS/DSi mode via the CLI would also be a great addition.
