### ISSUE TITLE
Input reaction time altered by some settings

### ISSUE THREAD

**Issue by Tatsuya79** [melonDS-emu/melonDS#1120]
I used the new framestep hotkey to do some tests: 
keeping a direction pushed down then counting how many frame steps it takes to see a move on screen.

In Mario Kart DS on the title screen:
-3 frames to see the selection moved in software
-9 frames in gl
-5 frames in gl with audio sync off

I wonder if there's something wrong here.

tested on win7 x64

**Comment by Ryunam** [comment]
This confirms that the regression initially spotted in the libretro core actually derives from upstream code. See here for the issue report that was posted in the libretro core repo: https://github.com/libretro/melonDS/issues/100

Based on my tests, I believe that these 2 frames of latency started to appear with the "upstream changes" that were referenced in this commit, dating back to January-February (exact timing could be different though): https://github.com/libretro/melonDS/commit/25ec9c05e58944631e5c59711d0e3948c7b4f0ba

**Comment by RSDuck** [comment]
the regression was introduced in https://github.com/Arisotura/melonDS/commit/a3f4aaf50314f6ab528afb8dbcef88cfb012e765

**Comment by Ryunam** [comment]
Hi, thank you for identifying the commit where this issue started. As it stands right now, unfortunately using the GL renderer in both the libretro core and standalone yields a noticeably unresponsive feel, with the input being particularly sluggish compared to software. I hope a workaround is possible and/or planned in the near future.

**Comment by Immersion95** [comment]
Any news on this matter ?

**Comment by Immersion95** [comment]
I'm sorry to bump this but it has been 2 years that the OpenGL core has 2 frames of input lag compared to Software. While I do appreciate all the other effort being done, I think this is an important matter.

Would it be possible to retract this commit https://github.com/melonDS-emu/melonDS/commit/a3f4aaf50314f6ab528afb8dbcef88cfb012e765 ?

**Comment by RSDuck** [comment]
I found the actual cause of the issue a while back and fixed it on the compute shader renderer branch (for both the OpenGL renderer and the compute shader renderer).

https://github.com/melonDS-emu/melonDS/commit/a3f4aaf50314f6ab528afb8dbcef88cfb012e765 only removed something which accidentally made it better

**Comment by Immersion95** [comment]
> I found the actual cause of the issue a while back and fixed it on the compute shader renderer branch (for both the OpenGL renderer and the compute shader renderer).
> 
> [a3f4aaf](https://github.com/melonDS-emu/melonDS/commit/a3f4aaf50314f6ab528afb8dbcef88cfb012e765) only removed something which accidentally made it better

Thanks a lot @RSDuck, sorry I didn't know it was somewhat fixed albeit in another branch. I suppose this wouln't be backported in the main build before the comppute shader branch is mature enough ? Have a great day :).

**Comment by Immersion95** [comment]
I built it myself and can confirm that it's working nicely :)

**Comment by Immersion95** [comment]
@RSDuck : Is the fix on the main build ? The compute shader branch is from Sept 2023 and I would love to use the newer builds.

**Comment by Immersion95** [comment]
This is solved thx to https://github.com/melonDS-emu/melonDS/pull/2041

This issue can be closed
