### ISSUE TITLE
Rendering Issue (Homebrew)

### ISSUE THREAD

**Issue by BrandonKaim** [melonDS-emu/melonDS#1143]
If you try running this on melonDS https://github.com/devkitPro/nds-examples/tree/master/Graphics/gl2d/dual_screen it only renders the bottom screen while the top is left completely blank, on real hardware both screens display shapes

**Comment by RSDuck** [comment]
the issue is direct boot, it works if the homebrew is booted through the firmware menu.

The firmware seems to initialise the polygon attr to disable the zero dot check which when enabled prevents the drawing on the topscreen which is only done using dots.

**Comment by RSDuck** [comment]
the issue lies in the zero-dot W check, which clips away all the dots which make up the graphics on the top screen.
