### ISSUE TITLE
Black Flashing When Playing at High Resolutions (OpenGL)

### ISSUE THREAD

**Issue by Peduls** [melonDS-emu/melonDS#1173]
When playing at high resolutions there's a persistent black flickering of the entire screen. Affects all games from what I can tell and becomes worse/more frequent the higher you set the resolution. These clips were taken at 16x times native resolution.

https://user-images.githubusercontent.com/34750422/128110150-625522a8-444c-4862-a632-c508f5131662.mp4

https://user-images.githubusercontent.com/34750422/128110200-d4d7a9ce-dc06-4b81-9b76-65c77fe614fb.mp4

**Comment by RSDuck** [comment]
could be a synchronisation issue.

**Comment by RSDuck** [comment]
> Might be a GPU driver issue.

yes should have been clearer. I wasn't talking about screen synchronisation, but about syncronisation between the emulation thread and the main thread.

**Comment by autofire372** [comment]
> 
> 
> > Might be a GPU driver issue.
> 
> yes should have been clearer. I wasn't talking about screen synchronisation, but about syncronisation between the emulation thread and the main thread.

Comment deleted. Sorry.

**Comment by autofire372** [comment]
Interestingly, I was able to reproduce this by using Nvidia Profile Inspector to put a 60FPS framelimit on melonDS. Is OP using an external frame limiter of some kind, perhaps?

**Comment by Peduls** [comment]
I have a 144hz display and have no frame limiter enabled through Nvidia Control Panel or Nvidia Profile Inspector. Using a GTX 1070 with the latest drivers.

**Comment by autofire372** [comment]
Hmm. I have a GTX 1070 Ti, but my drivers aren't current. Maybe try downgrading to driver 461.72 and see if that fixes it?

**Comment by Peduls** [comment]
I'll try that. I think this is related to #989 because when the screen flashes black it is in this exact same strange pattern/shapes as in this video.
![Screenshot 2021-08-04 at 14-54-31 Issues · Arisotura melonDS](https://user-images.githubusercontent.com/34750422/128253473-1d73c564-a27e-4a9e-ae11-56f6c6a97088.png)

**Comment by RafaelTrepaUnCarballo** [comment]
I suffer the same black flickering/tearing in OpenGL mode (Software mode is immune). It feels like Fastforwarding, Audio Sync or Alt+Tab make it worse.


> 
> 
> I have a 144hz display and have no frame limiter enabled through Nvidia Control Panel or Nvidia Profile Inspector. Using a GTX 1070 with the latest drivers.

I have a 120hz display, GTX 2060, 471.41 drivers (I'll update them as soon as I can)... it's a  laptop legion 5 15arh05h 82b1.

I wonder if this is a Nvidia issue or an emulation bug with high refresh monitors.

**Comment by nadiaholmquist** [comment]
This doesn't happen with AMD or Intel graphics on both macOS and Linux.

**Comment by RafaelTrepaUnCarballo** [comment]
I re-enabled the AMD integrated card of my laptop and the black flashing stopped.

So the bug is exclusively related to Nvidia and its windows drivers.

**Comment by MysticExile** [comment]
Enabling "Limit framerate" fixed this issue for me.

**Comment by SCOTT0852** [comment]
The "Limit framerate" option did not fix it for me. The issue does not occur on 0.9.1, the first stable version where it happened is 0.9.2 (and it is still present in 0.9.3). For what it's worth my hardware is a Ryzen 3600, GTX 1660 Super (driver 472.12), 16GB ram and the issue seems to start happening at 6x resolution.

**Comment by IceLancerSR** [comment]
This is no longer an issue. 
165hz monitor nvidia 1660 super. win10.
