### ISSUE TITLE
MelonDS is unable to boot up a ROM Hack of Pokémon White (1)

### ISSUE THREAD

**Issue by LOuroboros** [melonDS-emu/melonDS#1358]
Title.
MelonDS doesn't seem to be able to boot up a ROM of Pokémon Volt White 1, ROM Hack of Pokémon White 1 created by Drayano.
Desmume can do it though.

https://user-images.githubusercontent.com/4485172/152613102-0344c865-b952-4cb3-9d2d-89856b43a38d.mp4

I'm not sure if it's gonna be helpful, but here's my MelonDS .ini:
[melonDS.txt](https://github.com/Arisotura/melonDS/files/8006672/melonDS.txt)
*I renamed it to a .txt file because GitHub is picky about file formats.*

I checked if disabling the JIT Recompiler and swapping the graphics renderer helped, but no dice. The game refuses to boot up.

**Comment by patataofcourse** [comment]
This happens because melonDS emulates the IR stuff in Pokémon B/W, while most ROMs online stub it for use with flashcarts (see #1158). This hack does the same thing.
For fixing it, what you could try is opening the ROM in a hex editor and patching the title ID to D/P/Pt's

**Comment by LOuroboros** [comment]
> IIRC this happens because melonDS emulates the IR stuff in Pokémon B/W, while most ROMs online stub it for use with flashcarts (see #1158). This hack does the same thing. For fixing it, what you could try is opening the ROM in a hex editor and patching the title ID to D/P/Pt's

The title ID being the first 18 bytes, correct? I replaced them with `50 4F 4B 45 4D 4F 4E 20 50 4C 00 00 43 50 55 45 30`, Pokémon Platinum's, but it didn't work :eyes:

**Comment by patataofcourse** [comment]
in theory it would be whatever shows as the four character string INBx (x being E/P/J/etc depending on region), but maybe you can try loading it in melonds 0.9.1, because 0.9.2 was when IR emulation was added

**Comment by LOuroboros** [comment]
> in theory it would be whatever shows as the four character string INBx (x being E/P/J/etc depending on region), but maybe you can try loading it in melonds 0.9.1, because 0.9.2 was when IR emulation was added

That seems to work, thanks :eyes:

Gonna leave this ticket opened if you don't mind though. Ideally, this workaround shouldn't be required imo.

**Comment by LOuroboros** [comment]
Still happening in v0.9.5 :eyes:

**Comment by Epicpkmn11** [comment]
Tested on real hardware and IR works fine in Pokemon Volt White when running from nds-bootstrap, with the exact same ROM that freezes melonDS.

**Comment by RSDuck** [comment]
doesn't nds-bootstrap patch the saving on SDK level?

**Comment by Epicpkmn11** [comment]
Yeah, nds-bootstrap does some kinda patching to saving so I suppose that could be affecting something, but what #1597 is saying about IR being stubbed out in ROM hacks is clearly not true given that IR works perfectly fine in the ROM hack mentioned

I'm really not sure what's going on in the save patching so I'm not sure exactly if it's doing anything special to IR games or not, @RocketRobz might be able to say if there's anything that would affect this

**Comment by RocketRobz** [comment]
> I'm really not sure what's going on in the save patching so I'm not sure exactly if it's doing anything special to IR games or not, @RocketRobz might be able to say if there's anything that would affect this

How the save patching works in nds-bootstrap is the branches to the save chip R/W functions being replaced with branches to our own save file R/W code.
For games using THUMB arm7 binaries, the actual code gets replaced with jumps to our code, due to branch distance limitations.

**Comment by RSDuck** [comment]
Ok you were right afterall, it was something different.

This commit "broke" them: https://github.com/melonDS-emu/melonDS/commit/cd4ef575ee6e85e607e9a26a38af9d69d1cc69f3#diff-fd84b14d29012a982d0193020e7cba8e84f997806627e7b1fd81bde261b8b3a0

The romhack blanks the DSi header (likely happened during recalculation of some header checksums with a tool which wasn't aware).

https://github.com/melonDS-emu/melonDS/commit/ca7fb4f55e8fdad53993ba279b073f97f453c13c detects this and makes the cartridge a regular DS cartridge instead to fix it.

**Comment by Tosh0kan** [comment]
This problem is still very much present in the latest release.

**Comment by RSDuck** [comment]
the fix was commited after the lastest release.

**Comment by Tosh0kan** [comment]
Ah, okay. So I either have to wait for a new release or build it myself with the commit. Since I don't know how to do the latter, any idea when the former may happen?

**Comment by LOuroboros** [comment]
> Ah, okay. So I either have to wait for a new release or build it myself with the commit. Since I don't know how to do the latter, any idea when the former may happen?

Just so you know, you can download dev builds from the Actions tab of this repository.

![melonDS_20240314_023015380](https://github.com/melonDS-emu/melonDS/assets/4485172/5162f307-d297-4ea0-b253-312d565809d5)

![firefox_20240314_022035381](https://github.com/melonDS-emu/melonDS/assets/4485172/4c825ce9-8158-479a-b2de-bf3eb4a92662)
