### ISSUE TITLE
Make MelonDS for 32bit Windows

### ISSUE THREAD

**Issue by waterywater1** [melonDS-emu/melonDS#1361]
Please make a version for 32bit Windows
I am using Windows 7 32bit, so I can't use melonDS. I tried to find a version that works in 32bit OS, but there's none

**Comment by Arisotura** [comment]
what is your CPU?

**Comment by nadiaholmquist** [comment]
If you have a 64-bit capable CPU (chances very high), then it's time to upgrade your OS.

melonDS's JIT recompiler makes heavy use of the extra registers of x86_64 as far as I know, so porting it would be very hard and also nobody wants to do it.

If your CPU really can only do 32-bit it will have no chance of running full speed without JIT.

That said, melonDS can be compiled for 32-bit without JIT, but our build instructions require a 64-bit host.

**Comment by FrostKnight** [comment]
> If you have a 64-bit capable CPU (chances very high), then it's time to upgrade your OS.
> 
> melonDS's JIT recompiler makes heavy use of the extra registers of x86_64 as far as I know, so porting it would be very hard and also nobody wants to do it.
> 
> If your CPU really can only do 32-bit it will have no chance of running full speed without JIT.
> 
> That said, melonDS can be compiled for 32-bit without JIT, but our build instructions require a 64-bit host.

Does melonDS support 32 bit linux? 

just wondering, because if it doesn't, then it would be even more surprising if melonDS actually choose to do so.  

Aka, linux is more likely to make support easier.

But yeah, just curious.  Although, even some linux distros are dropping 32 bit.  

;)

**Comment by nadiaholmquist** [comment]
melonDS can be compiled no problem on 32-bit Linux but again without the JIT. In fact any little endian architecture should work.

We don't intend to provide 32-bit builds or JIT support but you're welcome to try it anyway.

**Comment by FrostKnight** [comment]
> melonDS can be compiled no problem on 32-bit Linux but again without the JIT. In fact any little endian architecture should work.
> 
> We don't intend to provide 32-bit builds or JIT support but you're welcome to try it anyway.

Hmm, hadn't realized this, the sad thing is, I don't know if the OP knows how to clone his operating system onto a usb 3.0, or use some flavor of 32 bit linux.
That honestly, is the only way that computer of his will probably be able to use melonDS, unless his hardware is 64 bit.

**Comment by nadiaholmquist** [comment]
If it's anything even remotely new (last 15 years +) and not from the bargain bin it will be able to run a 64-bit OS.

**Comment by FrostKnight** [comment]
> If it's anything even remotely new (last 15 years +) and not from the bargain bin it will be able to run a 64-bit OS.

Yeah, I would agree.  Out of curiosity, does your no 32 bit support, include armv7?

I assume so, but I wondered.

**Comment by nadiaholmquist** [comment]
Any little endian architecture will work, but the JIT recompiler only supports x86_64 and aarch64. If you compile for another architecture it'll be disabled and you're stuck with the interpreter (which on decent machines still does full speed).

This likely rules out 90% of ARMv7 and truly 32-bit only x86 CPUs from full speed, but it will run.

**Comment by yin846** [comment]
@waterywater1 I made 32 bit build but only briefly tested it on 64 bit Windows 10. 

I originally made this build because I wanted to test melonDS on 32 bit reactOS but it didn't work. But since you are running Windows 7 it will probably work but I haven't tried.

https://github.com/yin846/melonDS-builds/releases

**Comment by MyTDT-Mysoft** [comment]
> @waterywater1 I made 32 bit build but only briefly tested it on 64 bit Windows 10.
> 
> I originally made this build because I wanted to test melonDS on 32 bit reactOS but it didn't work. reactOS is currently aiming for compatibility with XP/server 2003 so that's why. Since you are running Windows 7 it will probably work but I haven't tried.
> 
> What CPU do you have? I'm curious. Also, please let me know how well it runs on your computer.
> 
> https://github.com/yin846/melonDS-builds/releases
> 
> Edit: I don't have a 32 bit windows 7 but I tried it on 64 bit windows 7.
> 
> https://www.youtube.com/watch?v=oLSGDIVbk80

what happened to your repository? i'm trying to make github itself to compile for 32bit with a workflow...

**Comment by Arisotura** [comment]
to make things clear:

* if you're stuck on a 32bit OS because your CPU is too old for 64bit: you're not gonna run melonDS anywhere near fast anyway
* if your CPU is 64bit capable: just, uh, upgrade to a 64bit OS

**Comment by Arisotura** [comment]
that's silly, you realize

it's kinda like if you had a hammer but insisted on using a rock to drive your nails in

anyway, good luck. you may find out that most of melonDS can be compiled for a 32bit platform and work fine. the JIT will require more work tho.

**Comment by MyTDT-Mysoft** [comment]
> that's silly, you realize
> 
> it's kinda like if you had a hammer but insisted on using a rock to drive your nails in
> 
> anyway, good luck. you may find out that most of melonDS can be compiled for a 32bit platform and work fine. the JIT will require more work tho.

yes... except this is also a hammer... i will also remove the QT dependency for windows... i would convert it to C instead of C++ to get some extra speed up, but that would diverge too much from the original, so i will leave that for last when the emulator stops being updated in the future... 

but since as is its just 10% slower than the 64bit version, (that i reverted just by using a -march target, since 64bit defaults to a newer march than 32bit as well), but yeah, i will try to maintain this better version of it for as long as possible :)

**Comment by Adamillo** [comment]
If you want I can try out your x86 fork. Just do me a favor and please update the build instructions on your fork so I can easily compile it for myself

**Comment by Arisotura** [comment]
> > that's silly, you realize
> > it's kinda like if you had a hammer but insisted on using a rock to drive your nails in
> > anyway, good luck. you may find out that most of melonDS can be compiled for a 32bit platform and work fine. the JIT will require more work tho.
> 
> yes... except this is also a hammer... i will also remove the QT dependency for windows... i would convert it to C instead of C++ to get some extra speed up, but that would diverge too much from the original, so i will leave that for last when the emulator stops being updated in the future...
> 
> but since as is its just 10% slower than the 64bit version, (that i reverted just by using a -march target, since 64bit defaults to a newer march than 32bit as well), but yeah, i will try to maintain this better version of it for as long as possible :), thanks and keep going!

I mean, your CPU is 64bit capable already, so what's the big deal about 64bit

**Comment by CasualPokePlayer** [comment]
> i will continue with the next step of having the JIT now to x86...

I bid you good luck at creating a x86 JIT from scratch along with a x86 JIT emitter from scratch, and for figuring out that monster 16GiB VirtualAlloc call.

**Comment by MyTDT-Mysoft** [comment]
> If you want I can try out your x86 fork. Just do me a favor and please update the build instructions on your fork so I can easily compile it for myself

oh you dont need to compile it yourself... i added a release... and a workflow so anyone can generate artifacts at any time with latest version... but yes, i will change the readme later, because i want to try to compile without msys2 as well, (it was just easier to have the workflow building for me, since it builds from linux)

**Comment by MyTDT-Mysoft** [comment]
> > i will continue with the next step of having the JIT now to x86...
> 
> I bid you good luck at creating a x86 JIT from scratch along with a x86 JIT emitter from scratch, and for figuring out that monster 16GiB VirtualAlloc call.

thanks... that will be fun part :D :D

**Comment by nadiaholmquist** [comment]
I'm not sure what the point of your fork and all those build script changes are? I just tried compiling it for 32-bit Windows and it works fine if you just install the dependencies for i686 instead of for x86_64.
