### ISSUE TITLE
Subtle Artifacting on Black 2 Titlescreen w/ Software & OpenGL Renderer

### ISSUE THREAD

**Issue by Jaklyy** [melonDS-emu/melonDS#1412]
Version: MelonDS 9.4 win64
Game: Pokemon Black 2 (US)
GPU: RX 480; w/ 22.3.1 drivers
CPU: intel i5-6400
Hardware images captured with an encrypted copy of b2 dumped via current version of gm9, run on nds bootstrap v0.55.2 via twlm++ v24.3.0 on a new3dsxl
Software images all captured with MelonDS 9.4, w/ bios + 128kb fw dump, using software renderer, w/ separate thread off, OpenGL display off, and jit off.

Issue: title screen with the camera panning around Kyurem has strange subtle artifacting on it.
Occurs on software & OpenGL, JIT on/off, with or without separate thread, with/without bios, etc.
Occurs on Desmume as well if that helps any.
Further hw verification might be needed if nds bootstrap screenshots aren't as lossless/accurate as I'm hoping.
I did try to check via running the cart natively though I lack a capture card to get a clear enough look.

MelonDS
![panning_down_wing_melonds](https://user-images.githubusercontent.com/102590697/161163935-040e7386-c38f-4a58-b13b-88170cc0eaa6.png)
Close up; still subtle
![close_up](https://user-images.githubusercontent.com/102590697/161164369-88a01b49-de0b-433d-82be-6d8c9ee46275.png)
Console
![wing_console](https://user-images.githubusercontent.com/102590697/161164185-0497cdce-8ba9-4f1b-a9eb-3f681e7cc437.png)
Console, close up; artifacting not present, wing appears smooth
![zoom](https://user-images.githubusercontent.com/102590697/161164455-40d30624-f6d9-4cd6-9994-5953e00e422a.png)
In motion it appears to be dragging some pixels into the lighter parts on MelonDS.

Visual issues are very noticeable when it cuts away to the tail.
![tail](https://user-images.githubusercontent.com/102590697/161164921-5b3ddf2f-ab83-4ded-a955-c9cb8e50d3b9.png)
The game does a quick cutaway (start of gif slowed down to make it more visible) with the previous scene not fully fading away on MelonDS.
![cutaway](https://user-images.githubusercontent.com/102590697/161164994-50f54172-85cc-4654-bf50-f082c45483b2.gif)
Though it appears to properly fade away fully on hardware.
![hw_tail](https://user-images.githubusercontent.com/102590697/161165235-6aad32d1-a2cd-41d3-9f50-8ead053c833e.png)

**Comment by Arisotura** [comment]
try it with the latest revision? maybe that will fix it

**Comment by autofire372** [comment]
Just updated and tested; I didn't observe any artifacts in either Software or OpenGL. Looks like you got it.

**Comment by Arisotura** [comment]
'aight, great! I'm testing the other blending/fade features to see if they've got similar shenanigans.

**Comment by Jaklyy** [comment]
Can also confirm it as fixed in black 2, and also that white 1's title screen is as well. (though you can now see the top corners of the checkerboard bg spazzing out in white, seems to occur on hardware too, just extremely subtly)
