### ISSUE TITLE
Fullscreen

### ISSUE THREAD

**Issue by 3lc3z4r** [melonDS-emu/melonDS#1459]
One question, do you plan to add the fullscreen when a game starts or give it a command line so that it runs better? (I say this more for the frontend that uses these elements) I know that it is currently but only as a form of hotkey, an option could be worth it

**Comment by sandwichwater** [comment]
not an actual feature of the emulator but if youre on windows you can go into the program properties and select the fullscreen on startup option

**Comment by 3lc3z4r** [comment]
> not an actual feature of the emulator but if youre on windows you can go into the program properties and select the fullscreen on startup option

well that option doesn't work for me much, I mean if it's in fullscreen but in the form of a window, of course unless you've done something wrong you can tell

**Comment by nadiaholmquist** [comment]
Once support for more command line parameters is added, `there's` a PR for this though I think it still needed some work, this will probably be supported.

**Comment by 3lc3z4r** [comment]
> Once support for more command line parameters is added, there's a PR for this though I think it still needed some work, this will probably be supported.
I love to hear that, thanks for the information

**Comment by 3lc3z4r** [comment]
> Once support for more command line parameters is added, there's a PR for this though I think it still needed some work, this will probably be supported.

I love to hear that, thanks for the information
