### ISSUE TITLE
Crash with Meteos Demo

### ISSUE THREAD

**Issue by lesserkuma** [melonDS-emu/melonDS#1471]
The DS Download Play demo version of Meteos crashes the emulator.

Affected No-Intro entries:
- Meteos (USA) (Demo) (DS Broadcast)
- Meteos (USA) (Demo) (Kiosk) (E3 2005)

The crash does not occur if the ROM is enlarged to at least 0x100001 bytes.

**Comment by KostaSaizo7** [comment]
This still happen with commit d5e313b378d1a43a57095e8cdfd8ef7543c299e9. To reproduce: boot Meteos, wireless>ds download play>select a planet and it gives a communication error

**Comment by lesserkuma** [comment]
> This still happen with commit [d5e313b](https://github.com/melonDS-emu/melonDS/commit/d5e313b378d1a43a57095e8cdfd8ef7543c299e9). To reproduce: boot Meteos, wireless>ds download play>select a planet and it gives a communication error

Hmm, seems like a different issue.
The issue I reported crashes the emulator entirely:

https://user-images.githubusercontent.com/67554470/191711139-bfe9b6bd-da8c-406d-9e39-661aa56f39d8.mp4

**Comment by KostaSaizo7** [comment]
> Hmm, seems like a different issue. The issue I reported crashes the emulator entirely:
True, I didn't notice that you refer to a demo rom. But the fact that the full game gives a communication error  when trying to enable ds download play, makes me think that there is some similarity to your issue.

**Comment by Arisotura** [comment]
I don't think the crash issue is related to wifi at all, more like that ROM has a fucked up header or something.

**Comment by lesserkuma** [comment]
Well it’s a DS Download Play binary, but the dump is good. It works without any problems if I send the binary over via DS Download Play between two instances of melonDS. The emulator also doesn’t crash if the file size is just increased with `00` value padding data to 0x100001 bytes.

**Comment by Arisotura** [comment]
that's interesting, I'll look into it later

**Comment by lesserkuma** [comment]
Thanks for the fix!
