### ISSUE TITLE
toolbar is rendered in opengl (along with the viewport)?

### ISSUE THREAD

**Issue by Zerowalker** [melonDS-emu/melonDS#1475]
I noticed that if i capture from melonDS it captures the toolbar as well (File, System, ...).
I take that as the toolbar is actually rendered along with the viewport, is that correct?
If that is correct then my request here is not render it that way so it's not captured along with the actual games being rendered.

Apologies for the bad description.

**Comment by Zerowalker** [comment]
oh?
Doesn't Dolphin also use Qt, and have a toolbar which acts the same as melonDS if you render inside the main window?
Cause it seems to behave different as it's not seen as being part of it when captured at least.

Not pointing fingers here, just wondering, if perhaps their approach can be used (unless that's what you meant by different rendering approach)?

Out of interest, what's the reasons for wanting to use a different rendering approach

**Comment by RSDuck** [comment]
we used to use QT's OpenGL widget, where QT just gives us an area to render to via OpenGL. We now use the same approach as dolphin where we let QT create a native window and render into it via OpenGL.
