### ISSUE TITLE
[Bug] Opening dialogue text not rendering properly - Chou Gekijouban Keroro Gunsou: Gekishin Dragon Warriors de Arimasu!

### ISSUE THREAD

**Issue by WaterBlad64** [melonDS-emu/melonDS#1482]
The dialogue text in this Japan-only Keroro Gunsou movie tie-in game's opening cutscene does not seem to render properly in MelonDS. Odd diagonal lines seem to render instead. This issue appears in both Software and OpenGL.

How it looks in MelonDS
![kerorodragonwarriors_melondstextrenderingissue](https://user-images.githubusercontent.com/43155513/179433975-bf1ae7af-5aa0-43ce-9e2c-21e57b10af35.png)
How it's supposed to look (taken in DeSmuME)
![kerorodragonwarriors_properlyrenderedtext_desmume](https://user-images.githubusercontent.com/43155513/179434013-857e5b94-9388-44a8-a353-5097bd629d92.png)

Edit: This issue seems to only affect the opening cutscene, subsequent cutscenes are unaffected.
![kerorodragonwarriors_properlyrenderedtext_melonds](https://user-images.githubusercontent.com/43155513/179443945-35e7da5e-f2f8-48b2-b595-3ed95cd62b75.png)

**Comment by Arisotura** [comment]
fixed by https://github.com/melonDS-emu/melonDS/commit/dd74e936ed69c7267ebb3f6d58634bd68cf7f642
