### ISSUE TITLE
ROM info dialogue - bannerless games aren't handled correctly

### ISSUE THREAD

**Issue by patataofcourse** [melonDS-emu/melonDS#1509]
NDS ROMs without a banner are characterized by having their banner offset nulled out - and aren't common aside from homebrew.
They look like this on the firmware menu.
![image](https://user-images.githubusercontent.com/29714419/187474325-19a0ed7a-783c-4800-b94b-2a85d146a863.png)
However, the ROM info dialogue doesn't handle this case correctly, and I assume tries to read banner data from the start of the ROM, resulting in the header being read as the banner. Here's how that looks.
![image](https://user-images.githubusercontent.com/29714419/187474855-829b195f-f317-4e18-9a4c-1cd2fc5cf8d4.png)
Should be a simple enough fix, but I have too much in my hands already so I'll just leave this here so it's known.

**Comment by RayyanAnsari** [comment]
Could you upload an example ROM?

**Comment by patataofcourse** [comment]
Of course! Here you have the libnds hello world example but bannerless
[why does it have to be a .zip](https://github.com/melonDS-emu/melonDS/files/9455585/why.does.it.have.to.be.a.zip)

**Comment by RayyanAnsari** [comment]
fixed by c3bd1d2e831e3e5cb0e1cc0bffc6eb9f29a94932
