### ISSUE TITLE
3D models glitching when using OpenGL

### ISSUE THREAD

**Issue by syncsyncsyncsync** [melonDS-emu/melonDS#1511]
Hey there,
Trying to play Pokemon Black 2 and encountered a problem when rendering 3D models that _are not_ the environment or part of the environment. So for example, on the opening screen, there's a 3D model of the Pokemon Black Kyurem that is absolutely massacred by really bad glitches. Here's a screenshot of what it looks like for me:
![image](https://user-images.githubusercontent.com/112657553/187992874-a9267236-abb5-469c-b140-7ab44ab0f859.png)
Vs. what it's meant to look like:
![image](https://user-images.githubusercontent.com/112657553/187993259-8075785b-a496-44a9-8032-101595d8c15f.png)
This does not occur when using software rendering. My GPU is an AMD RX 6800 (so p friggin beefy) and I'm using MelonDS 0.9.4 from the releases page.
Here are the drivers I am currently running:
![image](https://user-images.githubusercontent.com/112657553/187994965-659afbf3-aec6-449c-8733-95a0042b6574.png)

Any ideas? Thanks!

**Comment by Brankale** [comment]
AMD has a bad reputation when we talk about OpenGL drivers. Try to update the GPU drivers or switch to an old version if you already have the latest and see if this work.

**Comment by syncsyncsyncsync** [comment]
> 

Hey! Thanks so much for the help, it worked!! Much appreciated, stay safe :)
