### ISSUE TITLE
[bug] audio interpolation not fully functional

### ISSUE THREAD

**Issue by sandwichwater** [melonDS-emu/melonDS#1513]
hello , shown below is a recording that contains a few different examples of what audio interpolation sounds like in melonds and what the different bitrate settings sound like , then what interpolation sounds like in desmume , then what the raw audio sounds like played outside of an emulator . the game tested is kingdom hearts 358/2 days but i doubt the audio wouldnt get interpolated in just this game and this game alone . (sorry if theres any audio artifacts like clicking or watery sounding audio , just a result of trying to compress the video to under 10mb)

heres what it sounds like in melonds , every option seems to be extremely crunchy and harsh on the ears , the settings seem to change nothing but remove a slight white noise in each audio sample making up the sequence . if it makes any difference the first song played is streamed audio file , the other two are sequenced audio tracks . i just find it odd and unfortunate that melons interpolation doesnt seem to do much , if anything at the very least

https://user-images.githubusercontent.com/70611518/188298415-15a3aee3-5d4f-48f5-a901-9e2c14f9ce4b.mp4

now heres what it sounds like in desmume , the linear setting is what the audio would sound like raw not played through an emulator , or what an ideal interpolation implementation would sound like for the ds . although having only two options other than the ds one they sound miles better than melons interpolation , though the crunchy setting does sound worse than melons no interpolation setting . same as  before , first song is streamed audio , then the second two are sequenced

https://user-images.githubusercontent.com/70611518/188298564-3cd3f72e-d400-49bd-ba53-560196e741aa.mp4

lastly heres what it sounds like played raw without playing through emulation , the first program is playing the streamed audio file in a program called tinke which just plays the file as is , the sequenced audio tracks are played through a program called vg music studio . these are what desmumes interpolation sound like which is what they should sound like properly

https://user-images.githubusercontent.com/70611518/188298586-db567e45-087a-453e-a8be-a1aaff3467b6.mp4

**Comment by sandwichwater** [comment]
im not sure why the videos arent displaying ... thats weird

**Comment by Arisotura** [comment]
the melonDS core outputs audio at 32KHz (same sample rate as hardware). some games already have samples that are close to that frequency, so the interpolation setting does little. it's more effective in DeSmuME because it outputs audio at 44.1KHz.

that being said, atleast in desktop melonDS the core's output is upsampled to 48KHz, so we might do something there to make it sound smoother. (it's just, I tried before and it always sounded worse)

**Comment by sandwichwater** [comment]
thanks for explaining , id always wondered if the interpolation setting was just unfinished or the other settings werent functional since theres no real noticeable difference when desmumes interpolation seemed to work fine . though now ive got another question , if you were to end up doing something with the 48khz rate and making interpolation sound smoother would it function like desmumes does ¿

**Comment by sandwichwater** [comment]
fixed🎉
