### ISSUE TITLE
DS Phat firmware Download Play error

### ISSUE THREAD

**Issue by KostaSaizo7** [melonDS-emu/melonDS#1517]
As discussed in discord and in #1471, Meteos Download Play doesn't work with an external firmware. 

In DS mode, the first instance gives an error when initializing download play. To reproduce: boot Meteos, wireless>ds download play>select a planet and it gives a communication error.
![meteos](https://user-images.githubusercontent.com/39852873/192094669-fa8678f8-3015-4629-923b-39e1afcae0cc.png)

In DSi mode, it gets past the same error right after the second instances launches. 
![meteos1](https://user-images.githubusercontent.com/39852873/192094773-b17a3a46-5f55-4e4b-b212-c284d9fb9df1.jpg)

**Comment by Arisotura** [comment]
to be more specific: it breaks with a DSPhat firmware. for some reason it works fine with a DSLite firmware (and with an internal firmware, since the internal firmware is inited with DSLite wifi config).

**Comment by patataofcourse** [comment]
do we know if this breaks in dsphat hw?

**Comment by KostaSaizo7** [comment]
DSPhat firmware also causes problems in Super Mario 64 DS (thanks [Testsr](https://github.com/Testsr)). Download Play works fine with DS lite and DSi firmware.

![image](https://user-images.githubusercontent.com/39852873/201008743-dbca48dc-82ff-40ca-8e85-fc1d8c1a6e59.png)

**Comment by KostaSaizo7** [comment]
Made a list of Download Play issues in https://github.com/melonDS-emu/melonDS/issues/1518
