### ISSUE TITLE
Games that don't work in DSi mode

### ISSUE THREAD

**Issue by KostaSaizo7** [melonDS-emu/melonDS#1526]
Final Fantasy - The 4 Heroes of Light works fine in ds mode but in dsi mode it hardlocks in the main menu. The music keeps playing but the game is frozen. Similar thing happens if there is no save file. New game can be pressed, then you name your characters, and then black screen. I am booting the game from the dsi menu.

Log file: [Final Fantasy - The 4 Heroes of Light (USA).txt](https://github.com/melonDS-emu/melonDS/files/9741962/Final.Fantasy.-.The.4.Heroes.of.Light.USA.txt)

![image](https://user-images.githubusercontent.com/39852873/194766870-dfbc6048-f8f8-4429-aa79-d0b41dcd747e.png)

**Comment by KostaSaizo7** [comment]
I have found two more games with similar behavior:
Blue Dragon - Awakened Shadow freezes after company logos
Dragon Quest IX - Sentinels of the Starry Skies freezes on boot

**Comment by emir4169** [comment]
unless its installed to your nand DO NOT RUN STUFF FROM THE DSI MENU

**Comment by KostaSaizo7** [comment]
With "DSi mode"+"boot game directly", only the [DSi enchanced games](http://www.rfgeneration.com/blogs/pdrydia/DSi-enhanced-titles-an-incomplete-list-1969.php) boot at all

**Comment by emir4169** [comment]
Pokemon SoulSilver: Not even DSi enchanced versions work.

**Comment by patataofcourse** [comment]
Soul Silver isn't DSi enhanced, gen V are

**Comment by KostaSaizo7** [comment]
I made a list in issue #1548
