### ISSUE TITLE
fast forward/removing framerate limiter does not seem to change framerate

### ISSUE THREAD

**Issue by Riizade** [melonDS-emu/melonDS#1538]
System Details:
Steam deck purchased Oct. 1st
Installed melonDS via EmuDeck script
Using melonDS via Retroarch (as is the default config for EmuDeck)

I have configured the fast forward button, and pressing it displays the dual arrow icon (or when using rgui, the "fast-forward" text on screen) indicating that fast forward is active.

However, the framerate and frame time do not change, the game stays a solid ~60 fps and is not sped up at all.

Things I have tried:
- disabled vsync and audio sync
- tried the vulkan, glcore, and sdl2 renderers
- disabling the "OpenGL renderer" boolean toggle in the "Core Options" of RetroArch, and trying the above renderers again
- ran melonDS in "desktop mode" on the Steam Deck
- Reducing render resolution (in case the hardware happened to be straining to run at exactly 60fps, and simply couldn't push more pixels)

Behavior was the same for all of the above.

The most promising was running melonDS in desktop mode, as other users had success with that, but I did not.

I do not believe it's a machine power/speed issue, as I can run 3DS games via Citra at ~200% and Nintendo Switch games at ~160%.

The configuration I started with _should_ be fairly standard, because I literally just bought a standard steam deck and ran the EmuDeck script. No real steps inbetween.

Any ideas?

**Comment by patataofcourse** [comment]
The libretro fork is mantained by the folks over at libretro/melonDS, it's not supported by this team. RetroArch usually has more outdated versions of emulators so you might find the bug doesn't exist on the latest available version
