### ISSUE TITLE
[Bug] Text not displaying correctly in Crayon Shin-chan - Obaka Dainin Den - Susume! Kasukabe Ninja Tai! (Japan)

### ISSUE THREAD

**Issue by TakuikaNinja** [melonDS-emu/melonDS#1540]
I recently dumped my Japanese DS games/saves for safekeeping. This particular game fails to display text during dialogue cutscenes. 
The issue is easy to replicate; just boot the game and skip the logo splashes to watch the first cutscene. Changing the renderer does nothing. 
Current melonDS behaviour:
![Crayon Shin-chan - Obaka Dainin Den - Susume! Kasukabe Ninja Tai! (Japan) 2022-10-19 14 27 44](https://user-images.githubusercontent.com/43363447/196579723-db498d82-64cf-41b2-af97-7ee67e11d700.png)

Correct behaviour (DeSmuME):
![desmume-screenshot-0](https://user-images.githubusercontent.com/43363447/196580496-fe4a477b-a4a5-4cfd-b2a8-c7a6c09ffb41.png)

**Comment by RSDuck** [comment]
very interesting, the characters are sprites, so it's not a 3D engine edge case.

**Comment by RSDuck** [comment]
the sprites seem to be missing from OAM in melonDS.

**Comment by RSDuck** [comment]
sprite 24 contains the と hiragana in the top left corner. If the ARM9 timing is set to be very fast (data and code 1 cycle) a value can be found there different than when it's set to be slower, so this could be a timing issue. Though the sprites still don't display properly.

**Comment by Arisotura** [comment]
some technical notes on this:

sprite 23 is the first of the text sprites.

the OAM data for the text sprites is all wrong.

then entire OAM is DMA'd from mainRAM every frame:

ARM9 DMA3 84000200 00 020E3048->07000000 2048 bytes 32bit

the text sprites start at 0x070004B8, which is 0x020E3500 in the mainRAM buffer.

which is DMA'd by another transfer:

ARM9 DMA3 80000030 00 023282B5->020E3500 96 bytes 16bit

something seems wrong there, note the unaligned source address for this DMA transfer.

**Comment by TakuikaNinja** [comment]
Interesting. A similar issue might be occurring in #1482 too.

**Comment by Arisotura** [comment]
thanks for CasualPokePlayer for hinting at the issue, too -- I was going to spend hours backtracking the DMA source address :P
