### ISSUE TITLE
Pokemon Soulsilver only works on DS and not DSI

### ISSUE THREAD

**Issue by emir4169** [melonDS-emu/melonDS#1542]
the title. latest version of melonDS, legally dumped

**Comment by nadiaholmquist** [comment]
What happens when you try?

**Comment by emir4169** [comment]
White screen. Nothing

**Comment by Brankale** [comment]
The problem is with "Boot game directly" enabled which is a known issue

**Comment by emir4169** [comment]
> The problem is only with "Boot game directly" enabled which is a known issue

I tried without "Boot game directly" nope. same thing.

**Comment by Bonboon229** [comment]
I can confirm this issue with Platinum, Soulsilver, and White 1 and 2.

**Comment by KostaSaizo7** [comment]
The latest master https://github.com/melonDS-emu/melonDS/commit/4ef2e1f4ccc2f8046b74b8562c8ee8ef5d33d0b0 fixes the dsi direct boot. So I tried every pokemon game in both DS and DSi mode, directly and through the firmware menu. All of them boot, so try with the latest master. If the issue persists, you probably have a bad dump.
