### ISSUE TITLE
Specularity bug.

### ISSUE THREAD

**Issue by coderamen666** [melonDS-emu/melonDS#1545]
There is a bug where homebrew roms made with the nitro engine do not render properly if they use a shininess table. It works on real hardware, and Desmume. The code to the rom showing the bug is https://github.com/AntonioND/nitro-engine/blob/9e813fc6ef298b4bdd1ce81660dd6e89221fd143/examples/effects/specular_material/source/main.c

**Comment by jacobrogers256** [comment]
Is the rom needed to reproduce the bug.

**Comment by RSDuck** [comment]
hm the issue seems to lie in the lighting calculation (https://github.com/melonDS-emu/melonDS/blob/master/src/GPU3D.cpp#L1562-L1563). After subtracting fixed point one it's always less than zero so the shininess will always be zero.

**Comment by AntonioND** [comment]
For reference, this is the code that generates the table: https://github.com/AntonioND/nitro-engine/blob/9e813fc6ef298b4bdd1ce81660dd6e89221fd143/source/NEPolygon.c#L51-L59

Nothing special, just values between 0 and 255.

**Comment by RSDuck** [comment]
so I found this interesting comment and code in desmume's code: https://github.com/TASEmulators/desmume/blob/master/desmume/src/gfx3d.cpp#L947

and normalising the vector seems to really fix the issue. Though if this is really true that the vector is normalised it opens another giant rabbit hole: with how much precision is this operation done? Also taking the square root is an expensive operation which is probably pipelined which would implications on the timing model, though it would probably only need to be executed when the light direction changes (which desmume also uses an an optimisation).

**Comment by RSDuck** [comment]
here's my (terrible) code which makes the example work https://github.com/melonDS-emu/melonDS/tree/normalized-half-vec

**Comment by AntonioND** [comment]
I've updated the example in here: https://github.com/AntonioND/nitro-engine/blob/7ff191fe428c7f141adc58e1bb44f7565eae8871/examples/effects/specular_material/source/main.c

This is the result with DeSmuMe:

![specular_material](https://user-images.githubusercontent.com/6632664/197896854-fdbb48e5-7e86-4b6c-a694-a8658347ee64.png)

With melonDS, only the bottom screen is shown (which doesn't use the specular property, just the diffuse one).

This is the precompiled example:

[specular_material.nds.zip](https://github.com/melonDS-emu/melonDS/files/9864527/specular_material.nds.zip)

**Comment by jacobrogers256** [comment]
Are you using the fixed code?

**Comment by AntonioND** [comment]
No, I'm not going to compile the emulator myself.
