### ISSUE TITLE
multiplayer not working

### ISSUE THREAD

**Issue by Kyr4l** [melonDS-emu/melonDS#1561]
hi, i've been trying to play in MP with melonds with 2 machines, with no success after 2 hours and a half of attempts

i tried with 2 machines on the same network (linux & windows 11) firewall disabled, tried direct and indirect mode, no success

i tried with pokemon black and black 2, while running 2 instances on the same machine, it works. otherwise it won't work at all

how can i even firewall melonds ? i didn't find any documentation about ports and protocols in use but as i said i even disabled the firewall to be sure, nothing works

**Comment by RSDuck** [comment]
starting from 0.9.5 local wireless using interprocess communication and thus doesn't work across multiple computers.

**Comment by Kyr4l** [comment]
so if i undersand correctly, reverting to an older version would allow me to play with multiple computers ?

**Comment by RSDuck** [comment]
yes, although only badly, because 0.9.5 only really made it useable for general audiences (switching over to IPC was necessary for it to work as well as it does now).

**Comment by Kyr4l** [comment]
can you explain a bit further ? what's IPC ?

**Comment by patataofcourse** [comment]
IPC is inter-process communication, which means that two different melonDSs communicate with each other inside the PC rather than through the network

**Comment by Kyr4l** [comment]
so basicaly the feature was disabled or removed cause it wasn't good enough for the dev :(
quite sad

**Comment by RSDuck** [comment]
it just wouldn't be possible or much harder to get as smooth results via sockets. And even if we still would use network sockets, everything beyond connecting computers directly together with a LAN cable would have potential latency issues, so there isn't much of a usecase lost.

Local wireless over network is planned (with support for bigger latencies that playing over the internet would be viable), but with a different approach where everybody has to emulate all instances.
