### ISSUE TITLE
BUG: Saving a state with JIT enabled and loading it with JIT disabled crashes melonDS

### ISSUE THREAD

**Issue by lonkelle** [melonDS-emu/melonDS#1593]
Now, at first, you'd probably think that this bug isn't that big of a deal. But there's one operating system where JIT is only allowed **sometimes** and that's iOS (in which case JIT is disallowed on LTE but works on WiFi). 

Every other emulator that has JIT support including Dolphin, mupen64, PPSSPP, etc allows loading save states even if JIT is no longer available regardless of whether JIT was on when when the save state was made. 

melonDS is the exception to this and it basically forces every instance of front-ends using melonDS on iOS (RetroArch, Deltroid, Provenance, Delta) to **completely** disallow enabling JIT only on the DS console while supporting JIT on every other one. 

Now, I know a lot of emulators don't actually roll their own JIT code but I believe melonDS is one of the few that does meaning you're who I have to turn to (I develop for Deltroid and Provenance on iOS) to get this fixed for iPhone, iPad, and the Apple TV.

Now, if your response is "we'll accept a PR to fix this but won't fix this ourselves" which is a totally acceptable response to an edge case like this (given you don't build for iOS) - would you mind telling me and the two teams I work with why you believe your emulator happens to be the only emulator with this specific edge-case bug so we can have a head start on fixing this + PRing it for you?

PS. Thank you for making melonDS - you've genuinely made a lot of iPhone, iPad, and Apple TV owners supa happy. Cheers! 🍻

**Comment by RSDuck** [comment]
What you described seems to works perfectly fine with our normal melonDS 0.9.5. Unless you mean by enabling/disabling the JIT enabling or disabling it at compile time (I haven't tested that).

> Now, I know a lot of emulators don't actually roll their own JIT code but I believe melonDS is one of the few that does 

what do you mean by this? I don't know anything we do which is unusual.

**Comment by lonkelle** [comment]
> What you described seems to works perfectly fine with our normal melonDS 0.9.5.
Here's a screen capture of the behavior I'm experiencing (at runtime, not compile time):

https://user-images.githubusercontent.com/5572600/210405364-44dce02e-50e3-472d-8c45-1b2b44d452d9.mp4

**Comment by lonkelle** [comment]
Earlier versions of melonDS actually crashed the app when I attempted this. But your latest version just hangs as you can see in the video.

**Comment by lonkelle** [comment]
> This is getting off topic, but this is not true. Dolphin, mupen64 and PPSSPP all have JIT recompilers specifically developed for them.

Oh, that is def my misunderstanding then of their implementations. Everyone who reads this thread - disregard what I said about JIT implementations in other emus. 😅 

> I can reproduce the issue with Super Mario 64, it didn't seem to happen with Mario Kart (which was what I used to test earlier).

I would have never expected this issue to be game specific. Interesting...I'll start testing a bunch of games and see how common it is. Thanks for looking into this with me. I just wanna give iPhone, iPad, and Apple TV users the best experience possible.

**Comment by lonkelle** [comment]
@RSDuck Did your commit really just fix this behavior; a single line? 😲

**Comment by RSDuck** [comment]
it atleast fixed the issue in Mario 64.

That code is there to keep savestates compatible between interpreter and JIT, but I somehow messed up the condition, so previously it effectively did nothing. Thinking about it now it's kind of funny that this even sometimes worked.

**Comment by lonkelle** [comment]
Ha, woah, the power of a single punctuation in code can never be understated; you're amazing @RSDuck! Thank you for doing this for us (and so quickly too).

In theory, this should fix all games switching in-between the interpreter and JIT. I'll program the two front-ends I work on for iOS to enable JIT of melonDS in all cases from now.

I'll let you know if any games are "an exception" to your condition in a future issue. But here's to hoping that never happens (and it doesn't like it will). 🍻
