### ISSUE TITLE
[Feature Request] Libretro's Retro achievements

### ISSUE THREAD

**Issue by FoxbitDreamtail** [melonDS-emu/melonDS#1595]
You probably knew that this was coming but I would like to earn achievements in all the emulators I play on, gives a sense of achievement y'know?

**Comment by CasualPokePlayer** [comment]
Dupe of https://github.com/melonDS-emu/melonDS/issues/1146
Also, RetroAchivements is not owned by libretro folks, a separate community owns that

**Comment by FoxbitDreamtail** [comment]
> Dupe of #1146 Also, RetroAchivements is not owned by libretro folks, a separate community owns that (and saying it's owned by libretro does not do RetroAchivements any favors given the amount of drama behind libretro)

sorry, didn't realize but it would be cool nonetheless. I will search for these issues in the future.
