### ISSUE TITLE
Overflow flag not correctly calculated for adc

### ISSUE THREAD

**Issue by FluBBaOfWard** [melonDS-emu/melonDS#1596]
Adding 0x80000000 & 0xFFFFFFFF & Carry should not set overflow as it does on melonDS 0.9.5.

**Comment by RSDuck** [comment]
thanks for the report, should be fixed in https://github.com/melonDS-emu/melonDS/commit/8ec8a6ce09923a4bc721f7935cd6b16ad775a983 and https://github.com/melonDS-emu/melonDS/commit/eadfeec7abca813ff3c55fcf0fbf5b8fe2938730
