### ISSUE TITLE
[Feature Request] Disable IR emulation enforcement when a game has it disabled

### ISSUE THREAD

**Issue by AncientCarthage** [melonDS-emu/melonDS#1597]
My knowledge of coding is nonexistent, but from what I understand MelonDS Enforces IR emulation on games that have it, like Pokemon Black and White, which can crash those games if their IR functionality is intentionally disabled with something like a romhack or patch.  This is already a known issue, as you can see [here](https://github.com/melonDS-emu/melonDS/issues/1358).  Could MelonDS disable IR emulation instead of enforcing it, and instead give the user a warning message of some kind?  I would like to play Blaze Black at some point on MelonDS desktop and android.

**Comment by RSDuck** [comment]
it wasn't IR afterall, see #1358
