### ISSUE TITLE
Black Screen while running Plants V Zombies with a custom control layout

### ISSUE THREAD

**Issue by rBok6** [melonDS-emu/melonDS#1600]
I rearranged the screens on a custom control layout since PvZ is mostly touch, and whenever I try to use said layout the emulator won't show anything but a black screen and I think the audio is still present in the background but with no video input. If I switch to the default layout everything works fine.

This is running on a realme 7i device with android 10.

**Comment by RSDuck** [comment]
we don't develope or support the Android version.
