### ISSUE TITLE
[Feature Request] Mute Audio on Fast-Forward

### ISSUE THREAD

**Issue by Ezequiel0914** [melonDS-emu/melonDS#1605]
![Audio](https://user-images.githubusercontent.com/59774675/213290283-8a87d86d-0092-4009-aaa5-6d0ce6e04ff0.png)

Ideally this setting would be on audio, I'd rather not have to mute myself the audio everytime I fast-forward; thanks in advance!

**Comment by patataofcourse** [comment]
did you unintentionally close this issue?

**Comment by Ezequiel0914** [comment]
I saw two other issues requesting the same feature, dating Oct 24 and Jul 10 2022, respectively- So, I thought it was kinda redundant
