### ISSUE TITLE
Emu Settings Greyed Out 

### ISSUE THREAD

**Issue by Phononenom** [melonDS-emu/melonDS#1608]
I am running 0.9.5 on Ubuntu. Emu settings greyed out on my second launch, which defaults to a second instance. Deleting the config files created a third instance instead upon launch. Deleting the third config and restoring the previous two still create a third instance. Deleting the build folder and the config folder, and then rebuilding leads immediately to the third instance. I don't really care what instance works, as long as emu settings is no longer greyed out

**Comment by Arisotura** [comment]
this sounds like melonDS wasn't properly closed, which led to the IPC shared-memory and semaphore objects not being freed (because it works this way on Linux). there are commands to clear these, but I don't remember them on the top of my head.

**Comment by Phononenom** [comment]
My semaphore array is clear, and I am looking at my shmid's and don't see anyduplicates

**Comment by Arisotura** [comment]
there wouldn't be duplicates, because several melonDS instances will use the same sharedmem object. the way this works is that the sharedmem block contains a bitmask that is used to determine which number a new instance should get.

**Comment by patataofcourse** [comment]
Why close the issue?
