### ISSUE TITLE
Unable to Detect Platinum SAV

### ISSUE THREAD

**Issue by suckerforpokemon** [melonDS-emu/melonDS#1612]
Long story short, I transferred my HeartGold and Platinum DSV files from my old phone over to my PC and had them both convert to SAV (512 KB). Downloaded their respective NDS ROMs, HG worked just fine but Platinum insisted on not reading the SAV file. I read from somewhere that MelonDS experiences some difficulties reading the SAV files of some games, including Platinum (have not tried to replicate the issue with my other ROMs just yet, will be reporting on them once I get the chance). Anyone got any ideas as to how I can fix this issue?

Edit: The games that fail to recognize their respective SAV files are currently: Pearl, Platinum, Black, White and White 2. Rest of the games work just fine, even Black 2, but for whatever reason these select few are just being annoying little pricks.

**Comment by nadiaholmquist** [comment]
Are you entirely sure that the save files have the same file name as your ROMs?

For example, if you have `Pokemon - White Version.nds`, the save file needs to be named *exactly* `Pokemon - White Version.sav`.

**Comment by suckerforpokemon** [comment]
Oh, thank you! That was a tremendous help! Turns out the software that I used to convert the DSV files into SAV also changed their names a bit, should have realized that sooner. Sorry to be a burden, but do you also know why the game has 2 separate save files, one for both singleplayer and multiplayer each?

**Comment by RSDuck** [comment]
next time just use the import savefile feature in melonDS, it works with DSV files as well.
