### ISSUE TITLE
All 48 Possible Fullscreen NDS Screen Layouts

### ISSUE THREAD

**Issue by soundsnow** [melonDS-emu/melonDS#1623]
Swap, Rotate (90°, 180°, 270°), Hide, Big/Small
![image54](https://user-images.githubusercontent.com/109885044/218662614-03029d6b-8435-4705-8a1a-670f623dcbd5.png)

**Comment by patataofcourse** [comment]
melonDS doesn't support Android/iOS/any mobile operating systems (there's unofficial ports, but that's it), I don't get the point of this issue

**Comment by patataofcourse** [comment]
is this a duplicate?? #1604

**Comment by ashgx** [comment]
傻逼，别tmd来捣乱行吗，每个模拟器都发这种？老外能没想到？不玩电脑就别tmd往电脑端这边发ok？

**Comment by ashgx** [comment]
我还是讲清楚一些事情：第一，你提的建议在之前就已经有老外解释过了，你的说法在国内使用电脑的人基本上没有出现你说的那种情况；第二，我看了你向很多模拟器开发者提交了你这种潦草的设计图的建议，如果是玩家使用在安卓手机的那还可能接受，但是你的建议在玩家使用电脑基本上没什么作用；第三，如果你有去国内的bilibili网站，贴吧，甚至论坛上都有人明确表示，melonds电脑端是官方的，而安卓端melonds是非官方的，所以这边建议你别往这边提交这种实际没啥作用的建议。
