### ISSUE TITLE
Broken ds firmware emulation

### ISSUE THREAD

**Issue by erikiorai** [melonDS-emu/melonDS#1628]
ok i know melonDS is in early development but after i updated melon DS i can;t boot to ds firmware for DS download play and PictoChat
in older version the firmware was able to boot now its broken now im getting this error.
![εικόνα](https://user-images.githubusercontent.com/14198423/220407687-dd5d0706-32a4-4629-9657-f8f758b28306.png)
Do you have any plans to fix this

**Comment by RSDuck** [comment]
you need to go into emu settings and specify the path to the firmware files.

**Comment by Arisotura** [comment]
(and make sure you have external BIOS/firmware enabled)
