### ISSUE TITLE
linux wfc issue

### ISSUE THREAD

**Issue by A-childs-encyclopedia** [melonDS-emu/melonDS#1632]
the third step for wfc setup doesn't render properly
[image](https://imgur.com/a/YBy9IZX)

**Comment by patataofcourse** [comment]
what game is this? on what distro? is this with the flatpak pakage? opengl or software? builtin or external bios?

**Comment by A-childs-encyclopedia** [comment]
pokemon b2, pop os, flatpak, how do i check the last 2?

**Comment by A-childs-encyclopedia** [comment]
btw, it's on retroarch

**Comment by patataofcourse** [comment]
it's probably a bad bios or firmware dump, should be in emu settings, turn off "use external BIOS and firmware files"

**Comment by patataofcourse** [comment]
oh the libretro port is not supported here
head to libretro/melonDS for that

**Comment by A-childs-encyclopedia** [comment]
It works on standalone Melonds. Thanks for the help
