### ISSUE TITLE
cmake doesnt work on msys2 (command not found)

### ISSUE THREAD

**Issue by Xagarsan** [melonDS-emu/melonDS#1633]
Hi when I try to compile the files it says that the cmake command is not found, help pls I am new at this.

Here is the code:

$ cmake -B build
cmake --build build
cd build
../tools/msys-dist.sh
-bash: cmake: command not found
-bash: cmake: command not found
Run this script from the directory you built melonDS.

**Comment by CasualPokePlayer** [comment]
You skipped a step, installing cmake was placed before the compile step.

**Comment by Xagarsan** [comment]
But I followed the instructions without messing anything, sorry if im wrong it is my first time doing this.

If it is nor installed cmake, how can I do it

Thanks for the help

**Comment by Xagarsan** [comment]
> You skipped a step, installing cmake (along with other dependencies) was placed before the compile step.

look:

 $ pacman -S mingw-w64-x86_64-cmake
warning: mingw-w64-x86_64-cmake-3.25.2-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) mingw-w64-x86_64-cmake-3.25.2-1

Total Installed Size:  86.51 MiB
Net Upgrade Size:       0.00 MiB

:: Proceed with installation? [Y/n]

**Comment by CasualPokePlayer** [comment]
Did you open the `MSYS2 MinGW 64-bit terminal` (step 2)

**Comment by Xagarsan** [comment]
How do I do that? it is not this one?
![image](https://user-images.githubusercontent.com/127281426/223635747-49e5f919-a902-434d-b5ff-9cba50628237.png)

**Comment by CasualPokePlayer** [comment]
It's the "mingw64" one

**Comment by Xagarsan** [comment]
ok, anyway it gives me an error, 

$ cmake -B build
cmake --build build
cd build
../tools/msys-dist.sh
CMake Error: The current CMakeCache.txt directory C:/Users/XABIER.GARCIA/Downloads/msys64/home/XABIER.GARCIA/melonDS/build/CMakeCache.txt is different than the directory c:/Users/XABIER.GARCIA
/OneDrive - Claret Askartza/Dokumentuak/msys64/home/XABIER.GARCIA/melonDS/build where CMakeCache.txt was created. This may result in binaries being created in the wrong place. If you are not s
ure, reedit the CMakeCache.txt
CMake Error: The source "C:/Users/XABIER.GARCIA/Downloads/msys64/home/XABIER.GARCIA/melonDS/CMakeLists.txt" does not match the source "C:/Users/XABIER.GARCIA/OneDrive - Claret Askartza/Dokumen
tuak/msys64/home/XABIER.GARCIA/melonDS/CMakeLists.txt" used to generate cache.  Re-run cmake with a different source directory.
CMake Error: The current CMakeCache.txt directory C:/Users/XABIER.GARCIA/Downloads/msys64/home/XABIER.GARCIA/melonDS/build/CMakeCache.txt is different than the directory c:/Users/XABIER.GARCIA
/OneDrive - Claret Askartza/Dokumentuak/msys64/home/XABIER.GARCIA/melonDS/build where CMakeCache.txt was created. This may result in binaries being created in the wrong place. If you are not s
ure, reedit the CMakeCache.txt
El sistema no puede encontrar el archivo especificado
CMake Error: Generator: execution of make failed. Make command was: C:/Users/XABIER~1.GAR/ONEDRI~1/DOKUME~1/msys64/mingw64/bin/ninja.exe &&
Run this script from the directory you built melonDS.

**Comment by Xagarsan** [comment]
> It's the "mingw64" one

Hi again, I have accomplished to compile the melon DS emulator but when I open it it shows this error:
![image](https://user-images.githubusercontent.com/127281426/223660281-4a9832a0-e93d-49e7-8b9c-3e0abb1fe7d9.png)
