### ISSUE TITLE
Error opening melonDS emulator: "no Qt platform plugin could be initialized"

### ISSUE THREAD

**Issue by Xagarsan** [melonDS-emu/melonDS#1635]
Hi again, I have accomplished to compile the melon DS emulator but when I open it it shows this error:
![image](https://user-images.githubusercontent.com/127281426/223734549-3727d530-513e-4d83-aa42-cb69df3645d1.png)

**Comment by patataofcourse** [comment]
Which instructions did you follow- static or dynamic ones?
Also, how does your build folder look?

**Comment by Xagarsan** [comment]
I followed dynmamic ones, and this is my build folder:
![image](https://user-images.githubusercontent.com/127281426/223743963-1d111bc4-c156-4cac-bed5-245378bef6bf.png)

**Comment by Xagarsan** [comment]
> Which instructions did you follow- static or dynamic ones? Also, how does your build folder look?

Should I try the static one?

**Comment by Xagarsan** [comment]
> 

Thanks , it finally worked

**Comment by ElyesSellami** [comment]
Hello!

I faced this same issue when first trying to build the dynamic build for this. I was able to solve this issue by typing 
`pacman -S mingw-w64-x86_64-qt5-tools `
in msys2, in the melonDS folder. Hopefully it should work for you as well.
