### ISSUE TITLE
DSi title manager not working

### ISSUE THREAD

**Issue by duckfromdiscord** [melonDS-emu/melonDS#1641]
adding any title under DSi title manager causes the DSi NAND to never boot. it goes to the health and safety screen, then you tap, and then it goes to a black screen with the text "an error has occurred" on the bottom screen. I have tried adding two titles, one at a time. if you add it, it doesn't work, once you delete it again with the title manager, everything works again.

![image](https://user-images.githubusercontent.com/113956421/226628948-04e67c89-8388-4a32-b5ad-d7860e32c8cd.png)

if you dumped the NAND with titles already installed, those still work.

**Comment by RSDuck** [comment]
does the region of the title you installed match with the one from the NAND?

**Comment by darkreader2636** [comment]
Maybe NAND is full. Try copying games into emulated SD card via DSi Settings then try again

**Comment by duckfromdiscord** [comment]
> Maybe NAND is full. Try copying games into emulated SD card via DSi Settings then try again
@darkreader2636 

That was it. Thank you guys very much.
