### ISSUE TITLE
Quality of life Improvments (QOL)

### ISSUE THREAD

**Issue by MohamedSaif44** [melonDS-emu/melonDS#1652]
Easily the best emulator,but would you kindly add a **mute hotkey**.

**Comment by ElyesSellami** [comment]
I think this is a duplicate of [#1543](https://github.com/melonDS-emu/melonDS/issues/1543)

**Comment by MohamedSaif44** [comment]
weird,i thought i searched before,my bad.
i don't wanna be rude,but that's should be pretty simple right?i saw the duplicate was before the latest release.
