### ISSUE TITLE
0.9.4 and 0.9.5 issue with ROM hacks

### ISSUE THREAD

**Issue by koopa990** [melonDS-emu/melonDS#1659]
IT seems like the new versions do not play nicely with Pokemon black 2 ROM hacks. I had to downgrade to 0.9.3 to avert this. Future fix soon?

**Comment by patataofcourse** [comment]
this is because B2W2 romhacks use a rom with patched out IR code as a base. you can fix this by changing the ID of the ROM to platinum's or something like that

**Comment by koopa990** [comment]
> this is because B2W2 romhacks use a rom with patched out IR code as a base. you can fix this by changing the ID of the ROM to platinum's or something like that

How do I do that?

**Comment by RSDuck** [comment]
fixed by https://github.com/melonDS-emu/melonDS/commit/cd4ef575ee6e85e607e9a26a38af9d69d1cc69f3
