### ISSUE TITLE
"Failed to load the Rom" when launching a game from an external drive

### ISSUE THREAD

**Issue by EpicDog2** [melonDS-emu/melonDS#1664]
Im on Linux (Pop OS 22.04) using the flatpak package and when im trying to launch a game from an external drive I just get an error saying **"Failed to Load the Rom"**

**Comment by EpicDog2** [comment]
manged to fix this by using the appimage version

**Comment by patataofcourse** [comment]
ah yeah that's probably caused by flatpak's sandboxing in one way or another, wonder if it can be fixed somehow

**Comment by patataofcourse** [comment]
also, what appimage version? there's not any official ones as far as i can tell

**Comment by EpicDog2** [comment]
> also, what appimage version? there's not any official ones as far as i can tell

https://melonds.kuribo64.net/downloads.php
