### ISSUE TITLE
Failed to load rom from command line when file name has special character

### ISSUE THREAD

**Issue by Homaxz** [melonDS-emu/melonDS#1689]
I'm trying to run Pokemon SoulSilver from the command line as such:

`melonds.exe "C:\Users\ADMIN\Desktop\Pokémon - SoulSilver Version.nds"`

melonDS starts and gives the error "Failed to load the ROM."

Starting the rom from the GUI>file option works fine. 
Renaming the rom and to "Pokemon - SoulSilver Version.nds" makes it load through the cmd as well.

**Comment by RSDuck** [comment]
which version are you using, I think we fixed this one already.

**Comment by Homaxz** [comment]
Sorry I forgot to mention. 0.9.5

**Comment by RSDuck** [comment]
then it is a duplicate of #1556
