### ISSUE TITLE
DsiWare Manager not working x2

### ISSUE THREAD

**Issue by Josr278** [melonDS-emu/melonDS#1695]
En android no funciona el DSIware manager en firmware normal, pero en un firmware con Unlaunch integrado en la ".nand" si es posible añadir juegos de DSi sin embargo no encuentro ningun firmware con Unlaunch integrado en la nand de forma boot (osea que inicie con ese "Unlauncher")

**Comment by nadiaholmquist** [comment]
Android is not officially supported. You should report this issue to the developer of the unofficial Android port instead.

**Comment by qeeg** [comment]
DURR YES, I'M GOING TO LOOK AT AN ISSUE TRACKER THAT'S FOR ONE LANGUAGE ONLY (ENGLISH) AND SUBMIT AN ISSUE IN SPANISH THAT THE DEVS WILL NEVER UNDERSTAND WITHOUT SOME KIND OF TRANSLATION SERVICE, BECAUSE I'M AN INCONSIDERATE JACKASS :D

**Comment by Josr278** [comment]
> Android is not officially supported. You should report this issue to the developer of the unofficial Android port instead.

Ya veo gracias, ¿Tienes algun firmware con unlaunch integrado en la nand?

**Comment by nadiaholmquist** [comment]
Sorry we can't help you with that, we can't distribute Nintendo's copyrighted system files.
