### ISSUE TITLE
melonDS crashes when plugging in a controller

### ISSUE THREAD

**Issue by commandcontrolQ** [melonDS-emu/melonDS#1721]
```
OS: Windows 7 Professional 64-bit
Version: 0.9.4
```

## Context
I would like to play melonDS with another controller, ideally with an XBOX 360 Controller I had. 
It works fine on Windows 10, so maybe it will work on Windows 7, right?

## Problem
**It refuses to work.** If any controller is plugged in, then melonDS will refuse to open. 
If the controller is plugged in while melonDS is open, it hangs immediately.

## Steps to reproduce
- Make sure you have a controller on hand
- Install melonDS
- Plug the controller in after opening melonDS or before melonDS, the order doesn't matter

**Comment by nadiaholmquist** [comment]
Please retry this with the latest version.

**Comment by commandcontrolQ** [comment]
That seems to have worked. I wonder why?
Could it be because of this?
![image](https://github.com/melonDS-emu/melonDS/assets/124590064/380bf1ca-8a2c-4e23-9fcc-180300df67e5)

**Comment by nadiaholmquist** [comment]
No, that's unrelated. The most likely reason is that the library used for controller input was updated and that fixed whatever bug was happening.

...A legacy OS that is not receiving support anymore is probably not the main target for their testing.
