### ISSUE TITLE
Please, merge compute-shader-renderer branch already

### ISSUE THREAD

**Issue by v-fox** [melonDS-emu/melonDS#1799]
It's essential for playing Castlevania games. But recent changes to master branch have broken seamless patching due to b3d367a80c68614afc533805a78bb0420159ed79 commit being weird and replacing the whole file when it should (judging by manual comparison) only be mere:
```patch
--- src/NonStupidBitfield.h_A   2023-08-07 19:10:29.061598148 +0500
+++ src/NonStupidBitfield.h_B   2023-08-07 19:10:51.129722559 +0500
@@ -37,14 +37,14 @@
             return 0xFFFFFFFFFFFFFFFF << (startBit & 0x3F);
         if (((startBit + bitsCount) & 0x3F) && idx == startEntry + entriesCount - 1)
             return ~(0xFFFFFFFFFFFFFFFF << ((startBit + bitsCount) & 0x3F));
-        else
-            return 0xFFFFFFFFFFFFFFFF;
 
         return 0xFFFFFFFFFFFFFFFF;
     }
     else if (idx == startEntry)
     {
-        return ((1ULL << bitsCount) - 1) << (startBit & 0x3F);
+        return bitsCount == 64
+            ? 0xFFFFFFFFFFFFFFFF
+            : ((1ULL << bitsCount) - 1) << (startBit & 0x3F);
     }
     else
     {
```

**Comment by nadiaholmquist** [comment]
It will be merged when it's done. If you have the knowledge of programming to make that go faster then by all means contribute.

**Comment by v-fox** [comment]
> It will be merged when it's done. If you have the knowledge of programming to make that go faster then by all means contribute.

How it is "not done" if I have been using it for months not only without a single new issue but also WITHOUT ALL known bugs for Castlevania games [except for one](https://github.com/melonDS-emu/melonDS/issues/1466)?

> Also don't those games work fine with the software renderer?

I don't know but I do know that they look like shit with software renderer, especially 3D parts. It's bad enough that there is no texture/sprite filtering/upscaling but 1x resolution is atrocious.

**Comment by JesseTG** [comment]
Be nice. No one works on melonDS full-time; Rome wasn't built in a day.

**Comment by v-fox** [comment]
> Be nice. No one works on melonDS full-time; Rome wasn't built in a day.

And you think you can make assumptions, accusations and orders with no repercussions? Why don't you start with yourself first and lead by example?

Are there going to be any real answers or arguments other than ad hominems, gaslighting and baseless contrarianism?

**Comment by nadiaholmquist** [comment]
You got a perfectly good real response. Maybe it could have been more professional but when you start out a thread with such an entitled tone what did you think would happen?

There are still issues with rendering in some games, and I think issues with shader compilation taking a very long time with some drivers, it's also not properly hooked up to the UI yet. This all needs to be sorted out before it can be merged and all that work is done by someone volunteering in their spare time. It takes however long it will take, it's done when it's done.

As for the other PRs, they need to be reviewed by someone and there's realistically one person or maybe two who contribute that have the knowledge to do this.

**Comment by Adamillo** [comment]
Calm the heck down. The compute shader branch is not merged on master for a good reason. It's not finished, and there are some bugs that need to be fixed before it gets merged to master

**Comment by PoroCYon** [comment]
If you want things to be finished faster, consider donating some money to the project: https://melonds.kuribo64.net/donate.php

**Comment by v-fox** [comment]
> You got a perfectly good real response. Maybe it could have been more professional but when you start out a thread with such an entitled tone what did you think would happen?

If you start being combative from the word "Please", it is you who has some kind of problem. Throwing assumptions, orders, insults and orders is not a good "tone" either but, I guess, ganging up is OK thing to do here.

> There are still issues with rendering in some games, and I think issues with shader compilation taking a very long time with some drivers, it's also not properly hooked up to the UI yet.

These "issues" are not documented anywhere while issue that I have and that are listed here are gone for me. So I don't see whatever you all imagined for yourselves, so no need to throw your "entitled tone" on me just because you all got drunk on some feeling of authority.

> As for the other PRs, they need to be reviewed by someone and there's realistically one person or maybe two who contribute that have the knowledge to do this.

As a user I don't have time to wait "while entire Rome builds" when I have solution for my problem right here. It's been months already. If you want people to understand your secret problems then you may at least list them publicly first without jumping to conclusions and this swarming social-media-bully behaviour.

> If you want things to be finished faster, consider donating some money to the project: https://melonds.kuribo64.net/donate.php

Should I go to church and pray to you all while paying piety? So, personal attacks weren't enough, now it's extortion too? Should I pay all of you for your great mud-throwing service or only the guy who wrote the part I'm interested in?

**Comment by v-fox** [comment]
That just excellent: I asked you about status of work, you made up accusations, started out drama with entire gang and the only relevant piece of information being "some" unspecified "problems", then just silently swept it out under the rug with no actual answer or an apology for abhorrent behaviour.

No wonder that well-documented requests sit without so little as a comment for months, if not years, while the entire crew is gung-ho about a lecturing rampage.

Speaking of actual issues:
> shader compilation taking a very long time with some drivers, it's also not properly hooked up to the UI yet

From what I remember, compilation time is a driver issue and only for some specific models (may even be already fixed in drivers). For which current OpenGL and software implementations are still available.
And how could it be "not hooked up to the UI"? I sure didn't add it there myself.

This sounds like an implication that not a single one of you actually tested it and documented those issues even among yourselves, let alone started proper merging discussion with public issue listing. Without which any work could happen only on a whim, almost on accident, with zero planning (which mean: might as well be never).
Which may be a reason for some sense of insecurity from shame which is "alleviated" by creating justifications for personal attacks for shaming others. But that part I pulled from the same place as you did.

**Comment by Adamillo** [comment]
Plus, the compute shader branch is very WIP, and doesn't even have a PR. Do you expect it to be documented in terms of it's issues when it doesn't even have a PR?

**Comment by v-fox** [comment]
> I think you need to read through this thread again and realize who it is that is being needlessly argumentative here, mate. Because it sure as hell isn't me.

I came here to discuss a branch of code, not you or your inventions about my personality. You've said very little on the topic but very much about me, your feelings and how I supposedly obligated to goose-step around them.

> Yes, the issues with the compute shader renderer are not documented in the issue tracker, maybe they should be but they aren't. Oh well. They're known by the developer of it (Generic) and have been discussed in our chatroom already. This is not some extremely organized, professional open source project - things are done as people have the motivation to do them, and sometimes that's in a disorganized way that might take longer than people would like, such is life.

But this is the whole point of code tracking systems. And if even tracking is stagnate then there is little chance of any focussed effort to be possible. Private chats are bane of open software development.

> The UI issue I mentioned is that the compute shader renderer currently replaces the regular GL one, that obviously needs to be fixed, 

It's not, there is dedicated option that was there for months. Unless it secretly duplicated for both selections but my last comparisons convinced me otherwise.

> and the shader compilation issue happens on a fairly normal setup - i.e. nvidia drivers on Windows, so obviously that can't just be shipped like that either. Maybe these issues are already fixed and I just forgot about it, but the last time I tried it they were there and I don't remember them getting fixed yet.

But it works fine here with AMD on Linux. And you don't seem to be making snapshot builds or plan roadmap for an immediate release. Why not merge all non-suspect requests and start actually testing them ?

it's already getting bitroted with incompatibility with recent changes. Luckily, this time it was cosmetic and I could just remove stray duplicated lines. Next time it can be something substantial which means that any sane distro packager will have to permanently freeze-fork the package, so users could get latest working build with CSR option.

> Plus, the compute shader branch is very WIP, and doesn't even have a PR. Do you expect it to be documented in terms of it's issues when it doesn't even have a PR?

Which is **exactly** my point.
This is an essential change which does a giant leap forward in quality (it has been promoted for years as **the future fix** for most of graphical issues here), yet it sits abandoned and not even discussed. Worse yet, it seems that even you don't care to test it out, so there is even less chance of users trying it. Yet you have a lot to say about unrelated matters.

Since I only care about few games on DS, I'm going to finish them using forked patched build of the emulator and then never touch it again. But it's a shame for most users who will not be able to check them out with better solution which is available.

**Comment by RayyanAnsari** [comment]
GPLv3 sections 15 and 16 may be interesting to you.

**Comment by RSDuck** [comment]
this kind of escalated and I honestly don't want to pick up this discussion and argue point for point.

The compute shader renderer will be merged eventually. What is mostly left is unfortunately the most boring part, so I have been putting it to the side for a bit. Compilation of such complex shaders is pretty slow on some systems. So I need to implement a shader cache, otherwise for it to not take half a minute to start. There are also still some minor issues with very high scaling factors.

You might disagree with your developement practices, but we do things at our pace and they are admittedly from time to time a bit unorganised. But this is an emulator to play games on, this is fun, low stakes software and we do not have any real obligations to anyone.

Regarding the weird diff, thanks for bringing this up. Looks like I messed up and somehow commited a change in line ending. I fixed that, the branch is now mergeable again with no conflicts again.

**Comment by v-fox** [comment]
> GPLv3 sections 15 and 16 may be interesting to you.

@RayyanAnsari Have your entire crew not made enough of a job harassing me, so you've decided to chime in too ? Will you bring your whole family and social media "friends" next to take turns ? Should I leave you my physical mail address so you could send letters with same beaten-up horseshit every day for the end of time ?

If you'd spent 1/10 of that energy on anything productive then maybe you would have less urges for these juvenile defensive knee-jerk reactions.

---

@RSDuck

> this kind of escalated and I honestly don't want to pick up this discussion and argue point for point.

> You might disagree with your developement practices, but we do things at our pace and they are admittedly from time to time a bit unorganised. But this is an emulator to play games on, this is fun, low stakes software and we do not have any real obligations to anyone.

It's not the development practices that truly bother me, it's changing the subject into gang-led personal attack circus from the get-go.
Tendency for mismanagement and abandonment in projects are just unfortunate for everyone.

> But this is an emulator to play games on, this is fun, low stakes software and we do not have any real obligations to anyone.

I've been postponing my gauntlet of DS games (mostly last Castlevania titles on which Bloodstained is heavily based on) for entire decade. Luckily for me, you've made progress just in time for its end, so I've got almost all what I wanted out of it.

But just like most newcomers will not be able to patch community patches/mods into unbalanced/ugly-out-the-box Castlevania titles (GBA titles especially), they wouldn't be able to patch this emulator to play the series in proper way. Poor unfortunate souls.

> also regarding the software renderer PRs. We're in contact with the person working on them, who's constantly making new discoveries. As much as we unfortunately sometimes let PRs rot, this is not best example for this.

It is though. Contact in private chats does not let users know the progress. If it sits uncommented for months then it may as well be abandoned. I, personally, don't care about software renderer but changes there may show errors in other places that may affect stuff I care about too and the author seem to know what they are doing.

**Comment by v-fox** [comment]
And exactly what I was warning about has happened: PR[1800](https://github.com/melonDS-emu/melonDS/pull/1800/)  broke it due to `Refactor Platform::OpenFile and Platform::OpenLocalFile to accept a FileMode enum instead of a string` change. I've tried fixing it by doing analogous changes:
```patch
 src/OpenGLSupport.cpp | 43 +++++++++++++++++++++----------------------
 1 file changed, 21 insertions(+), 22 deletions(-)

diff --git a/src/OpenGLSupport.cpp b/src/OpenGLSupport.cpp
index 4cb0e97..d45f0e8 100644
--- a/src/OpenGLSupport.cpp
+++ b/src/OpenGLSupport.cpp
@@ -26,8 +26,7 @@
 #define XXH_STATIC_LINKING_ONLY
 #include "xxhash/xxhash.h"
 
-using Platform::Log;
-using Platform::LogLevel;
+using namespace Platform;
 
 namespace OpenGL
 {
@@ -73,7 +72,7 @@ void LoadShaderCache()
 {
     // for now the shader cache only contains only compute shaders
     // because they take the longest to compile
-    FILE* file = Platform::OpenLocalFile("shadercache", "rb");
+    FileHandle* file = OpenLocalFile("shadercache", FileMode::Read);
     if (file == nullptr)
     {
         Log(LogLevel::Error, "Could not find shader cache\n");
@@ -81,19 +80,19 @@ void LoadShaderCache()
     }
 
     u32 magic, version, numPrograms;
-    if (fread(&magic, 4, 1, file) != 1 || magic != ShaderCacheMagic)
+    if (FileRead(&magic, 4, 1, file) != 1 || magic != ShaderCacheMagic)
     {
         Log(LogLevel::Error, "Shader cache file has invalid magic\n");
         goto fileInvalid;
     }
 
-    if (fread(&version, 4, 1, file) != 1 || version != ShaderCacheVersion)
+    if (FileRead(&version, 4, 1, file) != 1 || version != ShaderCacheVersion)
     {
         Log(LogLevel::Error, "Shader cache file has bad version\n");
         goto fileInvalid;
     }
 
-    if (fread(&numPrograms, 4, 1, file) != 1)
+    if (FileRead(&numPrograms, 4, 1, file) != 1)
     {
         Log(LogLevel::Error, "Shader cache file invalid program count\n");
         goto fileInvalid;
@@ -107,9 +106,9 @@ void LoadShaderCache()
 
         u32 length, binaryFormat;
         u64 sourceHash;
-        error -= fread(&sourceHash, 8, 1, file);
-        error -= fread(&length, 4, 1, file);
-        error -= fread(&binaryFormat, 4, 1, file);
+        error -= FileRead(&sourceHash, 8, 1, file);
+        error -= FileRead(&length, 4, 1, file);
+        error -= FileRead(&binaryFormat, 4, 1, file);
 
         if (error != 0)
         {
@@ -118,7 +117,7 @@ void LoadShaderCache()
         }
 
         u8* data = new u8[length];
-        if (fread(data, length, 1, file) != 1)
+        if (FileRead(data, length, 1, file) != 1)
         {
             Log(LogLevel::Error, "Could not read shader cache entry data\n");
             delete[] data;
@@ -130,14 +129,14 @@ void LoadShaderCache()
     }
 
 fileInvalid:
-    fclose(file);
+    CloseFile(f);
 }
 
 void SaveShaderCache()
 {
-    FILE* file = Platform::OpenLocalFile("shadercache", "rb+");
+    FileHandle* file = OpenLocalFile("shadercache", FileMode::ReadWriteExisting);
     if (file == nullptr)
-        file = Platform::OpenLocalFile("shadercache", "wb");
+        file = OpenLocalFile("shadercache", FileMode::Write);
 
     if (file == nullptr)
     {
@@ -147,9 +146,9 @@ void SaveShaderCache()
 
     int written = 3;
     u32 magic = ShaderCacheMagic, version = ShaderCacheVersion, numPrograms = ShaderCache.size();
-    written -= fwrite(&magic, 4, 1, file);
-    written -= fwrite(&version, 4, 1, file);
-    written -= fwrite(&numPrograms, 4, 1, file);
+    written -= FileWrite(&magic, 4, 1, file);
+    written -= FileWrite(&version, 4, 1, file);
+    written -= FileWrite(&numPrograms, 4, 1, file);
 
     if (written != 0)
     {
@@ -157,7 +156,7 @@ void SaveShaderCache()
         goto writeError;
     }
 
-    fseek(file, 0, SEEK_END);
+    FileRewind(file);
 
     printf("new shaders %d\n", NewShaders.size());
 
@@ -166,10 +165,10 @@ void SaveShaderCache()
         int error = 4;
         auto it = ShaderCache.find(newShader);
 
-        error -= fwrite(&it->first, 8, 1, file);
-        error -= fwrite(&it->second.Length, 4, 1, file);
-        error -= fwrite(&it->second.BinaryFormat, 4, 1, file);
-        error -= fwrite(it->second.Data, it->second.Length, 1, file);
+        error -= FileWrite(&it->first, 8, 1, file);
+        error -= FileWrite(&it->second.Length, 4, 1, file);
+        error -= FileWrite(&it->second.BinaryFormat, 4, 1, file);
+        error -= FileWrite(it->second.Data, it->second.Length, 1, file);
 
         if (error != 0)
         {
@@ -179,7 +178,7 @@ void SaveShaderCache()
     }
 
 writeError:
-    fclose(file);
+    CloseFile(f);
 
     NewShaders.clear();
 }
-- 
2.41.0
```
Haven't tested it yet due to problem with build-server.

**Comment by beta215** [comment]
> > It will be merged when it's done. If you have the knowledge of programming to make that go faster then by all means contribute.
> 
> How it is "not done" if I have been using it for months not only without a single new issue but also WITHOUT ALL known bugs for Castlevania games [except for one](https://github.com/melonDS-emu/melonDS/issues/1466)?
> 
> > Also don't those games work fine with the software renderer?
> 
> I don't know but I do know that they look like shit with software renderer, especially 3D parts. It's bad enough that there is no texture/sprite filtering/upscaling but 1x resolution is atrocious. The fact that there is a plethora of ignored software renderer-related pull requests is not encouraging either.

And this is where the wrong stuff started happening...

Being rude **and** disrespectful with other people, and their work, doesn't opens any doors in life. Nobody here is working for a salary, neither owe anyone else anything. 

The reply to your original message was appropriate and a common response every other dev could give. Treat people the same way you would like to be treated - no excuses.

**Comment by v-fox** [comment]
> The reply to your original message was appropriate and a common response every other dev could give. 

So, toxic pile up from entire gang from a single sentence starting from "please" is a " common response every other dev could give"?

> Treat people the same way you would like to be treated - no excuses.

Also, why the hell are you adding one yourself after everyone else had a go? What exactly do you think to bring on an issue tracker with your toxicity?

Does this means that I have all rights to get 10 of my friends to shittalk every single one of you in completely unhinged and unrelated manner every day for entire month, right?

> And this is where the wrong stuff started happening...

"Wrong stuff" started happening from self-entitled personal attacks as if I owe you a courtesy to take them. It was not discussion about anyone, until you made it so.

Which is especially comical, since not a single person here actually tested or used the code in question, except for its creator. Or seem to be interested in closing plethora of obvious bugs, fix for which is available for months due to someone who actually done the job and humbly kept quiet. So their, and yours, input is absolutely useless.
