### ISSUE TITLE
Puzzler World cannot create a save file and won't load past error screen.

### ISSUE THREAD

**Issue by bardemz** [melonDS-emu/melonDS#1804]
As far as I am aware, this is not a DSi game.

The sequel (Puzzler World 2 aka Puzzler World 2011) runs just fine.

![259561233-cfe30e57-989b-4999-a67b-819956aee3fa](https://github.com/melonDS-emu/melonDS/assets/107502478/df3d6cc1-27a7-4020-a6dd-df34e3f3e50c)

**Comment by CasualPokePlayer** [comment]
The issue here is likely just the wrong save type is being used. DeSmuMe seems to say it should be a 8KiB save file, while melonDS has a 128KiB save file.

**Comment by CasualPokePlayer** [comment]
Changing it to be a 8KiB (or 64KiB?) save file seems to have the game work fine. I could guess 8KiB is just correct given that is also what the European version is given by melonDS (which works fine)
