### ISSUE TITLE
Connect with real DSi

### ISSUE THREAD

**Issue by MHYCWasTaken** [melonDS-emu/melonDS#1817]
Is it possible to play game with a real dsi  
I didnt really know how dsi and dsi connect work so heres this question  
I want to play zelda spirit track and mario cart with my friend but we dont got 2 dsi

**Comment by RSDuck** [comment]
this is not planned. It might be possible to realise on Linux if you have a wifi card which supports monitor mode as I recently learned, but we haven't evaluated the latency of this. Besides there would be a lot of other issues to take care of it.

In short it would probably be very fiddly if it works at best, so this is not planned.
