### ISSUE TITLE
Regression after commit #d69745b3

### ISSUE THREAD

**Issue by Brankale** [melonDS-emu/melonDS#1819]
This commit d69745b3 introduces strange shadow casting in the intro video of `The Legend of Zelda Spirit Tracks`. This behaviour is not present on real hardware.

before
![melonDS 0 9 5](https://github.com/melonDS-emu/melonDS/assets/45881310/c9754245-d934-48f0-b082-3e118bb472fc)

after
![melonDS latest](https://github.com/melonDS-emu/melonDS/assets/45881310/5516a56b-c748-4392-9241-74c4639f08b1)

before
![Immagine 2023-08-28 144428](https://github.com/melonDS-emu/melonDS/assets/45881310/bba3b569-cdbd-4664-8d80-d85ba1fbf23d)

after
![Immagine 2023-08-28 144757](https://github.com/melonDS-emu/melonDS/assets/45881310/39cb54dd-fdec-4db5-9de4-9f50a22fa884)

other images
![Immagine 2023-08-28 145358](https://github.com/melonDS-emu/melonDS/assets/45881310/e3d33192-b277-4ed2-b553-d3340531ec23)

**Comment by Brankale** [comment]
The problem is

``` 
bool facingview = (dot <= 0);
```

This fixes the issue:
```
bool facingview = (dot < 0);
```

This thing was also mentioned in the pull request #1816 as a possible candidate for regressions.

**Comment by Brankale** [comment]
I will not open a pull request since I'm not sure if this change was necessary. @Jaklyy Can you check if this is correct?

**Comment by Jaklyy** [comment]
this would fix the regression, while reintroducing the bug this fix was aiming to resolve
correct fix seems to be to use <= only for determining if a polygon is supposed to be clockwise/counterclockwise
working on a fix right now
