### ISSUE TITLE
I can't start the DSi firmware.

### ISSUE THREAD

**Issue by Rix565** [melonDS-emu/melonDS#1827]
Each time I try to launch the DSi firmware, the emulator can't go past the initial white screen and spam this on the terminal:
undefined ARM9 instruction CD707B75 @ 037B8000
Trying to go to the title manager shows this, which I find a little worrying because it should find titles?? (I even tried replacing the nand, firmware, etc, with some backups on a backup hard drive but still nothing).
NAND: !! no title dir (0:/title/00030004)

I guess this is a regression? Because before on my older master build of melonDS the DSi firmware worked just fine.
This started to happen once I compiled the master branch.

It's quite bad for me in my case, since I am very nostalgic on the whole DS family of systems, and my DSi motherboard has fried, and until now, my only way to launch my old DSi was using the dumps and melonDS.

**Comment by KostaSaizo7** [comment]
I can reproduce this

This started happening after PR #1818 was merged

**Comment by Rix565** [comment]
Oh god so I'm not the only one, this is worrying...

someone should revert #1818 for the time being

**Comment by Rix565** [comment]
@KostaSaizo7 it seems that its even an older commit that breaks DSi functionnality, trying to run the CI builds of the commit just behind this one also fails to launch the DSi firmware.

**Comment by KostaSaizo7** [comment]
> @KostaSaizo7 it seems that its even an older commit that breaks DSi functionnality, trying to run the CI builds of the commit just behind this one also fails to launch the DSi firmware.

Odd, I just tried this build and it works https://github.com/melonDS-emu/melonDS/actions/runs/6003267380

**Comment by Rix565** [comment]
Huh? Im gonna try the AppImage then.

**Comment by RSDuck** [comment]
I can reproduce what @KostaSaizo7 sees.

**Comment by Rix565** [comment]
I'm gonna try to delete settings then.

**Comment by Rix565** [comment]
**NEVERMIND!!**
I was in the wrong directory, I was executing the latest commit all along. @KostaSaizo7 was right lmao

**Comment by RSDuck** [comment]
fixed in https://github.com/melonDS-emu/melonDS/commit/1aaf22d181e55abb8ad27be89ebae106b1c1cfcf
