### ISSUE TITLE
Error with the Compute Shader

### ISSUE THREAD

**Issue by Zer077** [melonDS-emu/melonDS#1838]
When I open any game, the screen does not load graphically well, I show images:

Super Mario 64 DS:
Compute Shader
![imagen](https://github.com/melonDS-emu/melonDS/assets/47561709/a16e9e11-0c4d-41e1-a83e-774b942c11cf)

OpenGL Classic:

![imagen](https://github.com/melonDS-emu/melonDS/assets/47561709/b93c642a-48cc-4e76-8b76-9af278f154c7)

Software: 

![imagen](https://github.com/melonDS-emu/melonDS/assets/47561709/9b704d66-7dca-443b-bf55-52f62c912a05)

Other examples:

![imagen](https://github.com/melonDS-emu/melonDS/assets/47561709/2182ee81-551d-4243-b88d-43473dd7566c)
![imagen](https://github.com/melonDS-emu/melonDS/assets/47561709/140c7d50-a9bc-451f-8227-3438279ee5e1)
![imagen](https://github.com/melonDS-emu/melonDS/assets/47561709/00e9ac9b-bb59-4235-8de0-84ad4c58cb68)

Seems to happen when there are "3D" things on the screen

@RSDuck I hope this helps you

**Comment by Zer077** [comment]
I try this on Steam deck and on my pc with 1650 ti i going to try on my 3070 too

**Comment by Zer077** [comment]
yes, on my 3070 is bad too

**Comment by RSDuck** [comment]
did you built it from latest source?

**Comment by Zer077** [comment]
yes, the last source of your branch compute-shader-renderer, im building again, just in case...

**Comment by RSDuck** [comment]
looks like the shaders fail to build on mesa, I'll fix this quickly.

**Comment by Zer077** [comment]
Oh, thanks!

**Comment by RSDuck** [comment]
ok, I gitted wrong and didn't have the latest changes on my Linux partition. Now I got everything up to date and the shaders all build, but I can reproduce the exact issue you have.

**Comment by Zer077** [comment]
Thank you so much, and good job with the computer shader, works perfect!
