### ISSUE TITLE
Not working on Sonoma

### ISSUE THREAD

**Issue by HugoNeves** [melonDS-emu/melonDS#1891]
I've installed MelonDS using Homebrew and everything was working perfectly on Ventura.

After upgrading the MacOS to Sonoma it just quits unexpectedly right after opening it. I'm using a Mac M1.

**Comment by nadiaholmquist** [comment]
I didn't know homebrew even packaged melonDS. It's not an official build so you'll have to poke them about it instead.

Does the build from the website work for you?

**Comment by HugoNeves** [comment]
> I didn't know homebrew even packaged melonDS. It's not an official build so you'll have to poke them about it instead.
> 
> Does the build from the website work for you?

Looking at the cask code (https://github.com/Homebrew/homebrew-cask/blob/2b26f2c482cfd2096ff387c00e3173538f5b8e94/Casks/m/melonds.rb) it seems they just use the 0.9.5. dmg file from this repo.

What do you mean by build from the website?

**Comment by nadiaholmquist** [comment]
I meant that dmg.

Can you post the error you get when it crashes? There's an issue that slipped into 0.9.5 that you might be hitting.

**Comment by HugoNeves** [comment]
> I meant that dmg.
> 
> Can you post the error you get when it crashes? There's an issue that slipped into 0.9.5 that you might be hitting.

https://gist.github.com/HugoNeves/b2a302fd45b7717cb96c73d0995706f1

**Comment by nadiaholmquist** [comment]
I *think* this might be that known issue. Can you try going to `~/Library/Preferences/melonDS` and rename/move the `melonDS.ini` and see if it starts?

**Comment by HugoNeves** [comment]
> I _think_ this might be that known issue. Can you try going to `~/Library/Preferences/melonDS` and rename/move the `melonDS.ini` and see if it starts?

Yes, it works now.

It crashed the first few times when I tried opening a save file, but after some tries and letting it go once to the in-game menu to load a save it works.

I (understandably) lost all the previous configurations I had, after renaming the ini file. Comparing the old file and the newly created one, these are the only differences:
```
HKKey_Pause=80
HKKey_FastForward=16777217
HKKey_FullscreenToggle=70
WindowWidth=1912
WindowHeight=930
ScreenSwap=1
ScreenSizing=3
ShowOSD=0
MPAudioMode=2
AudioVolume=256
MicInputType=0
RecentROM_1=/Users/path/to/a/rom
MouseHide=1
PauseLostFocus=1
```
These are what I have in my old ini file. I've tried putting it back and it crashed again, so I'm assuming one of these is creating an issue.

**Comment by nadiaholmquist** [comment]
`MPAudioMode=2`
Yeah I thought so. Please don't change that setting in 0.9.5 or it'll crash.

**Comment by HugoNeves** [comment]
> `MPAudioMode=2` Yeah I thought so. Please don't change that setting in 0.9.5 or it'll crash.

I've put back my old ini file, only changing that setting to 1. All good.
