### ISSUE TITLE
32-bit binary? Extremely specific use case.

### ISSUE THREAD

**Issue by LanHikariDS** [melonDS-emu/melonDS#1894]
I've seen an issue or two about this that have devolved into chaos without a real resolution. I'm trying to get MelonDS running on a dumbass system I can't upgrade to 64-bit (I spent the last two hours trying). Unlike the last issue I saw asking, I _don't_ need it to be an up to date build, and it doesn't even need good performance in most games. All I'm concerned with is reasonable speed running the DS firmware, and command line parameters (specifically '-f -b always'). I considered trying Desmume (as suggested in prior issue), but Desmume doesn't support actually booting the firmware.

EDIT for more details: Specifically, I'm trying to use a Lenovo Thinkcentre 300 Stick I specifically bought for this purpose, which (so I read online) _does_ have a 64-bit CPU, the _bootloader_ is 32-bit, so I can't install a 64-bit OS on it. While the hardware should be able to do more, even 5fps is acceptable for my use case, since I just need the RTC to stay in sync (which it can do even pausing and unpausing). Also unlike the aforementioned last guy, I _do_ have access to a 64-bit system I can use to compile this, but I still need the combiled binary to run on the 32-bit system.

**Comment by CasualPokePlayer** [comment]
DeSmuMe does support booting firmware.
![image](https://github.com/melonDS-emu/melonDS/assets/50538166/7c3fd4db-c4b3-43e2-a6f3-764c2f51d743)
(you still have to give it some kind of ROM, but it'll first go to firmware as long as that's checked and you have valid bios/firmware files present)

melonDS should compile fine for a 32 bit target (probably works under mingw32 with msys2), but it's not going to be preforming well as it will be stuck with the interpreter, which is not something you want to be pairing with a 32 bit build.

**Comment by LanHikariDS** [comment]
I tried following the build instructions but using mingw32, and got held up trying to run CMAKE to build. Msys2 is totally new territory for me, I usually just use Visual Studio to compile, and I've never even tried targeting Win32 there

**Comment by LanHikariDS** [comment]
> DeSmuMe does support booting firmware. ![image](https://private-user-images.githubusercontent.com/50538166/286159986-7c3fd4db-c4b3-43e2-a6f3-764c2f51d743.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExODg5MzMsIm5iZiI6MTcwMTE4ODYzMywicGF0aCI6Ii81MDUzODE2Ni8yODYxNTk5ODYtN2MzZmQ0ZGItYzRiMy00M2UyLWE2ZjMtNzY0YzJmNTFkNzQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDE2MjM1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1OWJjNWU2NzZjYWZjMWI2YmY3ZWRkMGVhMzM2MDc2NjFlMjU4ZWUzYTQ3MmE4Y2Q0Y2U5MGUyMTlkYWJjN2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ef1haH7Zru0MvhiCbq-G9CDrFaXfyKsPRgP6p6uA7gM) (you still have to give it some kind of ROM, but it'll first go to firmware as long as that's checked and you have valid bios/firmware files present)

I did not see this option, I'll double check my Desmume later

**Comment by RayyanAnsari** [comment]
If you don't post the error then we can't really help you to fix it.
It should work if you follow the Windows instructions but instead launch the 32-bit environment, install the i686 packages, and make sure to turn JIT off before building.

**Comment by CasualPokePlayer** [comment]
Instead of `pacman -S mingw-w64-x86_64-{cmake,SDL2,toolchain,qt5-static,libslirp,libarchive,zstd}` you want `pacman -S mingw-w64-i686-{cmake,SDL2,toolchain,qt5-static,libslirp,libarchive,zstd}`

**Comment by JesseTG** [comment]
I'm curious, what are you looking to do with a 32-bit build of melonDS that's allowed to run slowly?

**Comment by LanHikariDS** [comment]
> I'm curious, what are you looking to do with a 32-bit build of melonDS that's allowed to run slowly?

Literally _just_ display the DS Firmware's clock/calendar on an unused monitor at my work desk. I've gotten all the bullshit set up to get Desmume to do it, but it was a lot more of a hassle than I would've liked. It took me five minutes to set up melonDS to autoboot the way I wanted it to, but working around not being able to run MelonDS on the target hardware took maybe six hours of fanangling.

> Instead of `pacman -S mingw-w64-x86_64-{cmake,SDL2,toolchain,qt5-static,libslirp,libarchive,zstd}` you want `pacman -S mingw-w64-i686-{cmake,SDL2,toolchain,qt5-static,libslirp,libarchive,zstd}`

Did that and 'cmake --build build' gave me a massive error. Got Desmume set up with Autohotkey, so I'm not going to pursue this any further.
