### ISSUE TITLE
IRQ_RTC not being fired

### ISSUE THREAD

**Issue by nbvdkamp** [melonDS-emu/melonDS#1915]
The following program, compiled with devkitPro, is supposed to print the Unix epoch to the screen, updating every second.
```c
#include <nds.h>
#include <stdio.h>
#include <time.h>

int main(void)
{
	consoleDemoInit();

	while (1)
	{
		swiWaitForVBlank();
		time_t t = time(0);
		iprintf("\x1b[0;0HTime = %lld", t);
	}
}
```
It works on real hardware (and no$) but on melonDS it only updates on start and when the lid is closed and reopened.
I did some digging in libnds and what updates the value seems to be either the ARM7 being (re)initialized or [this line](https://github.com/devkitPro/libnds/blob/b37c88de856b8e0e8d4ea99b54c7f27b0ed5ec40/source/arm7/clock.c#L221) incrementing it.
That function is called by [the interrupt corresponding to bit 7](https://github.com/devkitPro/libnds/blob/b37c88de856b8e0e8d4ea99b54c7f27b0ed5ec40/source/arm7/clock.c#L278), called `IRQ_RTC` in melonDS's codebase.

I haven't been able to find any documentation on the interrupt's exact behaviour and don't know if this issue will be very useful but it puzzled me for a while so I thought I'd write it up at least.

**Comment by RSDuck** [comment]
it was implemented not too long ago. https://github.com/melonDS-emu/melonDS/pull/1867

Commercial software doesn't use it (except for the alarm in the firmware menu as far as I am aware), so it wasn't much a problem.

BlocksDS has a workaround for this btw: https://github.com/blocksds/libnds/commit/743ef395138150c958afb80b6a5ae2a58c8fe4be

**Comment by nbvdkamp** [comment]
Oh nice, thanks for letting me know.
