### ISSUE TITLE
Having some troubles in Galaxy S23

### ISSUE THREAD

**Issue by JoaoRestier** [melonDS-emu/melonDS#1943]
Hello guys
I'm having some troubles with melonds in Galaxy S23. The emulator is not recognizing bios and firmware files, and it's crashing when I try to put a cheat database. When I put the .XML, the app crash suddenly. I've tried others cheats database, and It still crashing.

Can you help me?

https://github.com/melonDS-emu/melonDS/assets/80717845/5a02000a-183d-4ba5-95c5-6919c303c26e

**Comment by JesseTG** [comment]
The Android port isn't developed or maintained by the melonDS team; you'll want to get help for it [here](https://github.com/rafaelvcaetano/melonDS-android).

**Comment by JoaoRestier** [comment]
Thank you, Jesse!

**Comment by JesseTG** [comment]
No problem.
