### ISSUE TITLE
[EMULATOR BEHAVIOUR] Blow Noise doesn't blow microphone

### ISSUE THREAD

**Issue by Ivan951236** [melonDS-emu/melonDS#1946]
In a specfic game called Penguins of Madagascar, The, Blow Noise option doesn't blow in a specfic Cake 2.0 stage's minigame about blowing one of collectable's (that kowalski later uses them to build stuff) dust out of one collectable in level 1
The video's download link (mediafire) contains more proof to see for yourself
https://www.mediafire.com/file/3ph7pr1k7zk0vcj/2024-01-09_19-46-31.mp4/file
unfortualy yes you have to download the video to see it but it is worth it

**Comment by dylndreams** [comment]
did u emulate in ds or dsi?

**Comment by dylndreams** [comment]
dsi cant do mic apparently
