### ISSUE TITLE
[Feature request] Add support for retroachievements.

### ISSUE THREAD

**Issue by Amnesia1000** [melonDS-emu/melonDS#1948]
I know there are more important things to discuss, but it would be nice in the future to have compatibility with retroachievements achievements. And have some type of notification when you manage to unlock an achievement, in addition to having the possibility of being able to see the achievements obtained and obtainable.

**Comment by JesseTG** [comment]
If you have itchy thumbs, the [new melonDS libretro core](https://github.com/JesseTG/melonds-ds) supports RetroAchievements and is up to date with the most recent commit.

**Comment by Amnesia1000** [comment]
First, I'm going to delete the issue because there are already other repeated ones. When I searched, I misspelled the word achievements and found no results. Now discover that there is already. Second, I prefer standalone emulators, I am not a fan of Retroarch or multi-emulators. Thank you very much in advance for responding.
