### ISSUE TITLE
ROMs not loadable from non-ASCII file paths

### ISSUE THREAD

**Issue by lesserkuma** [melonDS-emu/melonDS#1959]
**System used:**
Windows 11 23H2

**Build used:**
https://github.com/melonDS-emu/melonDS/actions/runs/7586469528

**Problem:**
Can't load ROMs from a path including characters that are not native to the operating system language.

**Steps to reproduce:**
1. Rename a confirmed working ROM file to something like `あああ.nds`, or copy it into a directory path with such non-ASCII characters.
2. Try to load it with melonDS via any means (File → Open ROM..., Drag & Drop, or Command Line).
3. Error message "Failed to load the ROM." appears.

**Comment by RSDuck** [comment]
was already fixed a few days after 0.9.5 release #1556

**Comment by lesserkuma** [comment]
Ah thanks! I couldn't find it via search.

I tested it on this build btw., should the fix not be implemented into it?
https://github.com/melonDS-emu/melonDS/actions/runs/7586469528

**Comment by RSDuck** [comment]
yes

**Comment by lesserkuma** [comment]
Hmm, the issue is definitely still there with this build from January 19th, 2024. Or it's a different issue, I'm not sure.

**Comment by RSDuck** [comment]
looks like it is a regression. I just tested it and it used to work.
