### ISSUE TITLE
Tales of Innocence broken upscaling

### ISSUE THREAD

**Issue by Remna319** [melonDS-emu/melonDS#1960]
Hey guys, i am trying tales of innocence to upscale the graphics but the upscaling switches from frame to frame back to 1x and 5x (alternating). This happened even at the intro cutscene. The is 3d on top screen and just a plain image with clock on bottom screen. I am using steam steck with emu deck and standalone melonds in desktop mode without any differences.

is there a way to fix this? Mario card seems to upscale correctly with map on bottom screen a racing on top screen?!

![IMG_1782](https://github.com/melonDS-emu/melonDS/assets/91380210/fd761af4-a3a1-4dce-9d9a-15c2337bb26b)
![IMG_1781](https://github.com/melonDS-emu/melonDS/assets/91380210/0a930ec9-a23f-4de7-9558-c2b7c322cc36)

**Comment by RSDuck** [comment]
probably needs hires display capture

**Comment by Remna319** [comment]
> probably needs hires display capture

What do you mean by that? I just want to play the game upscaled without jagged edges. No need for capture gameplay. As you can see at one image the frame is crystal clear rendering and the next it is total garbage. But with 60fps you will see just blurry messy graphics. >.<

**Comment by RSDuck** [comment]
display capture is a function in the DS's GPU hardware to save frames to memory which is what the game is very likely using. Thing is that melonDS is currently unable to preserve the high resultion of such memory frames when they're later used.

**Comment by Remna319** [comment]
> display capture is a function in the DS's GPU hardware to save frames to memory which is what the game is very likely using. Thing is that melonDS is currently unable to preserve the high resultion of such memory frames when they're later used.

So there is nothing right now to play high res in that game with Melonds? Is that feature worked on or in pipeline right now or planned for future updates?

**Comment by RSDuck** [comment]
it is a planned feature, but nothing more

**Comment by user18081972** [comment]
This seems to be fixed in the Blackmagic3 #2553 PR build
