### ISSUE TITLE
3D models freak out when 3D renderer is set to OpenGL

### ISSUE THREAD

**Issue by SilentWhisperer** [melonDS-emu/melonDS#1961]
https://github.com/melonDS-emu/melonDS/assets/119686757/a8724159-1091-423e-a79d-29afc15eedd7

Video of the issue (I don't know why obs didn't capture the whole window but oh well ┑(￣Д ￣)┍)
Fresh download of MelonDS, save imported from DeSmuME
Computer specs:
<img width="456" alt="image" src="https://github.com/melonDS-emu/melonDS/assets/119686757/733fcba5-cdbe-4699-bf54-26ecab6debc9">
<img width="418" alt="image" src="https://github.com/melonDS-emu/melonDS/assets/119686757/8e4b7977-3866-40a0-80c0-1ffb8e8e4e35">
<img width="204" alt="image" src="https://github.com/melonDS-emu/melonDS/assets/119686757/4dacdec4-7484-4c0a-8bf9-22cba9abb506">
Graphics drivers up to date

**Comment by SilentWhisperer** [comment]
i found out why obs captured only part of the screen at least xP

**Comment by Jaklyy** [comment]
looks like an amd gpu driver bug that got fixed a couple months back
is it running melonds on the igpu for some reason?
not sure how you'd tell that for sure though..
should be able to choose which gpu it runs melonds with, either somewhere hidden in the windows settings or nvidia settings

**Comment by SilentWhisperer** [comment]
yea making windows use my nvidia card fixed the problem
thanks a lot :)
<img width="1280" alt="image" src="https://github.com/melonDS-emu/melonDS/assets/119686757/17c39134-80e4-4483-93f4-abf1e2a64038">
