### ISSUE TITLE
(DSi) TLoZ: Four Swords Anniversary Edition emulation problems

### ISSUE THREAD

**Issue by tina379** [melonDS-emu/melonDS#1983]
I've been trying to play this game for a few days now and I've landed on using melonDS to emulate it but every time I try to open the rom I just get a white screen. I've downloaded all of the proper firmware for Dsi mode so I think the issue is with the rom itself. If anybody has any advice for what to do or a link to a rom that works that would be much appreciated, I've never tried emulating a Dsi game before so this is all new territory for me.

**Comment by RSDuck** [comment]
you need to install DSiware onto the DSi nand. Use the melonDS title manager for this.

**Comment by tina379** [comment]
> you need to install DSiware onto the DSi nand. Use the melonDS title manager for this.

Ok that worked. Thank you so much!
