### ISSUE TITLE
Using the DSP in a homebrew application crashes melonDS on linux

### ISSUE THREAD

**Issue by AntonioND** [melonDS-emu/melonDS#1993]
I'm trying to run the examples of BlocksDS with melonDS. With version 0.9.5 they work correctly, but they crash with the current master branch (SHA1 e227902cecfb629fd113e9fd7c69cea6b98dd790):
```
$ melonDS-master dsp_cmd_reply.nds
melonDS 0.9.5
https://melonds.kuribo64.net/
IPC sharedmem doesn't exist. creating
IPC: instance ID 0
Opened "/home/antonio/.config/melonDS/melonDS.ini" with FileMode 0x11 (effective mode "r")
Opened "/home/antonio/.config/melonDS/melonDS.ini" with FileMode 0x20 (effective mode "ab")
Opened "/home/antonio/.config/melonDS/melonDS.ini" with FileMode 0x12 (effective mode "w")
zsh: segmentation fault (core dumped)  melonDS-master dsp_cmd_reply.nds
```
The problem seems to happen even with trivial DSP ROMs that only use the CMD and REPLY commands to communicate the ARM9 and the DSP, like this one: https://github.com/blocksds/sdk/tree/5382e70feb852bd894719275713909c8b2226168/examples/dsp/cmd_reply

I'm attaching the binary I've used for that last test, as well as the elf and map files. However, you can build it yourself with BlocksDS on Linux (the Teak toolchain isn't available on Windows, but you can use it with WSL): 
[cmd_reply.zip](https://github.com/melonDS-emu/melonDS/files/14488428/cmd_reply.zip)

**Comment by AntonioND** [comment]
Using `git bisect` I've found the commit that introduced the error, but it's pretty big: https://github.com/melonDS-emu/melonDS/commit/bb42c8b6392e4e99634dc52137d2974781192482

**Comment by RSDuck** [comment]
I cannot reproduce on Windows, I'll look at it on Linux (UBsan and asan) later.

**Comment by AntonioND** [comment]
Thanks. I've just tested it and it looks like it also happens with ROMs that don't use the DSP, so it is probably just related to the changes to the save data code.

**Comment by nadiaholmquist** [comment]
if you try to run that build of melonDS without giving it a ROM, does it also crash?

**Comment by AntonioND** [comment]
Yes, even without a ROM it crashes.

**Comment by nadiaholmquist** [comment]
Ah, you're probably hitting the issue that a lot of people are running into right now then. DSi mode will crash on launch unless `ExternalBIOSEnable` is set to 1 in the config and you have valid paths for all DS and DSi BIOS/firmware.

**Comment by AntonioND** [comment]
Ah, right, that seems to be the issue. Now it complains that my dumps aren't valid, for some reason (but I got them from my own console, so I'd hope they are valid?).

**Comment by AntonioND** [comment]
Okay, I've just had to add every single BIOS file to the `.ini` file, including the DS mode BIOSes. Now it works!

**Comment by AntonioND** [comment]
I assume there is at least another issue keeping track of that bug, so feel free to close this issue, thanks for the help!
