### ISSUE TITLE
melonDS corrupting my DS firmware after changing WFC setting.

### ISSUE THREAD

**Issue by 72888hshu** [melonDS-emu/melonDS#2002]
Video demonstrastion:
https://youtu.be/0BPmI_HPRLI

**Comment by ashgx** [comment]
我看了一下为啥不把固件复制到硬盘上？而是在sd卡里？？？

**Comment by 72888hshu** [comment]
> 我看了一下为啥不把固件复制到硬盘上？而是在sd卡里？？？

主要是因为分类好了，刚刚试了移去SSD没问题了。
