### ISSUE TITLE
9.5 pokemon blaze black save file isn't recognized

### ISSUE THREAD

**Issue by Pollothumbsup** [melonDS-emu/melonDS#2003]
Just like title, I installed the 9.5 version of melonds, and started playing a rom hack of black and white. the load states work just fine, but the actual save isn't recognized and whenever I load the rom it asks me to start a new game. The .sav  file is 512 kb

**Comment by Pollothumbsup** [comment]
found out it works with an older dev build, it's just the latest one that doesn't recognize save files

**Comment by RSDuck** [comment]
can you tell us with which revision it works and with which it doesn't?

**Comment by Pollothumbsup** [comment]
> can you tell us with which revision it works and with which it doesn't?

The windows #2307 version works, as another user suggested in #1358  
The one I've had trouble with, that doesn't recognize save files is the latest windows #2320
