### ISSUE TITLE
bug(DevTools): break on startup has no effect

### ISSUE THREAD

**Issue by axel7083** [melonDS-emu/melonDS#2007]
## Bug

When selecting `break on startup` the game does not break at startup

https://github.com/melonDS-emu/melonDS/assets/42176370/7ff3224e-f5bf-4940-a3f3-3afd5a90e7a4

## Reproduce

Tested with master https://github.com/melonDS-emu/melonDS/commit/31a7f53282040c7df93204d647de470390b96c4b 

- (1) git checkout 
- (2) follow build instruction standalone windows
- (3) start emulator
- (4) change settings for AMR9
- (5) restart the emulator
- (6) boot a game
- (7) no break

**Comment by axel7083** [comment]
@PoroCYon  do you have some ideas ?

**Comment by PoroCYon** [comment]
sorry, don't really have time to look into it

could you try bisecting between 3ab752b and 31a7f53 to see which commit introduced the bug? there's been some refactoring going on so it could be something like that

**Comment by RSDuck** [comment]
from a glance it looks like GDB args are only passed in when the NDS object is created (https://github.com/melonDS-emu/melonDS/blob/10798c3464ca0e199087960fda918ed99acc2e21/src/frontend/qt_sdl/EmuThread.cpp#L145). They should be updated here as well https://github.com/melonDS-emu/melonDS/blob/10798c3464ca0e199087960fda918ed99acc2e21/src/frontend/qt_sdl/EmuThread.cpp#L295

Though then the setting should work under the condition that the setting was enabled during the construction of the NDS object (i.e. program startup or when switching between DS or DSi mode).

**Comment by PoroCYon** [comment]
> Though then the setting should work under the condition that the setting was enabled during the construction of the NDS object (i.e. program startup or when switching between DS or DSi mode).

Yeah, this was also a limitation from before the refactoring.

**Comment by RSDuck** [comment]
Please try again with the latest commit. GDB protocol parsing has been improved.
