### ISSUE TITLE
Accidentally enabled C-Gear in Pokemon Black 2 - Now I crash upon in-game saves

### ISSUE THREAD

**Issue by Dannydog123** [melonDS-emu/melonDS#2020]
Playing Pokemon Black 2 using melonDS on Delta for ios. Here is my save state with the issue I appreciate any help
![help 2](https://github.com/melonDS-emu/melonDS/assets/168046368/7b792092-17da-41d0-80bc-9a272072c0fb)

**Comment by Dannydog123** [comment]
Woops that was just an image file sorry mobile is killing me. Working on getting the actual file

**Comment by Dannydog123** [comment]
[savehelp.zip](https://github.com/melonDS-emu/melonDS/files/15102500/savehelp.zip)

Hopefully this is it

**Comment by nadiaholmquist** [comment]
[savehelp.zip](https://github.com/melonDS-emu/melonDS/files/15102548/savehelp.zip)

**Comment by Dannydog123** [comment]
I tried using that save state and still seem to be freezing on in game save or when attempting to turn off c-gear. Thank you so much for the help!

**Comment by nadiaholmquist** [comment]
maybe the archive program fucked up putting it in the zip... try this one? 
[savehelp(1).zip](https://github.com/melonDS-emu/melonDS/files/15102653/savehelp.1.zip)

**Comment by Dannydog123** [comment]
I got it working! Thank you so much you are so kind!
