### ISSUE TITLE
Set FPS Limit to 120 instead of 60

### ISSUE THREAD

**Issue by andrewjc03** [melonDS-emu/melonDS#2034]
Hi,

Is there any way I can modify the code to change the FPS Limit from 60 FPS to 120 FPS. The reason for this is that I want to play the game in 2x speed, but when I don't limit framerate it goes really fast (like 4x speed).

Any help on this would be appreciated.

Thanks,
Andrew

**Comment by KostaSaizo7** [comment]
Download the latest build from github and change the limit in Interface settings
![image](https://github.com/melonDS-emu/melonDS/assets/39852873/0bb8e3fb-e427-43ba-a602-3dce4c1b1282)
