### ISSUE TITLE
melonDS relies on 2's complement for shifting

### ISSUE THREAD

**Issue by CasualPokePlayer** [melonDS-emu/melonDS#2055]
Putting this as an issue here, this issue first was noticed in BizHawk builds (now fixed) although still shows up in upstream melonDS (using clang 18.1.6). The issue ends up manifesting into weird rendering issues with the software renderer.

Fix would be either putting in `-fwrapv` or bumping up the C++ standard to C++20 (where 2's complement is mandated and various UB shift operations are no longer UB). The latter option appears to have unrelated build failures, so the former seems like a simpler fix.

**Comment by Arisotura** [comment]
Could you point me to specific examples of this?

**Comment by CasualPokePlayer** [comment]
https://github.com/melonDS-emu/melonDS/compare/e234385c2008...cbb0f4b872ea
