### ISSUE TITLE
Game & Watch Collection 1 - Alarms don't sound

### ISSUE THREAD

**Issue by DandelionSprout** [melonDS-emu/melonDS#2066]
- <b>Problem:</b> The "Alarm Set" function doesn't ring when the set time is reached, e.g. "PM 12:50", regardless of whether the active mode at the time is "Time", "Game A", "Game B", the "Alarm Set" menu, or the main menu.
- <b>Tested on melonDS:</b> With and without DS firmware, started in DS Mode both directly and from the DS firmware menu, system time set accurately to real time in the DS firmware settings.
- <b>Additional testing:</b> TWiLight Menu++ on a Nintendo 3DS couldn't get the alarm to work either, making me wonder if it could be a major bug within the game itself, regardless of what https://www.nintendolife.com/reviews/2009/04/game_and_watch_collection_ds claimed back in 2009.
- <b>Screenshot(s):</b> The alarm bell icon shows up in <i>Donkey Kong</i>, but the icon stays there when the alarm time is reached, as opposed to Donkey Kong Jr. in the lower right jumping with a bell:
<details>

![image](https://github.com/melonDS-emu/melonDS/assets/22780683/af7b6f66-bd8c-46bf-b0a5-74b4f4ba02ff)
</details>

**Comment by Arisotura** [comment]
it is probably using the RTC alarm feature, which as of now is only implemented in nightly builds

**Comment by DandelionSprout** [comment]
I was able to get the nightly build at https://github.com/melonDS-emu/melonDS/actions/runs/9467786201, and it turned out you were indeed 100.0% right. Thanks for the tip.
