### ISSUE TITLE
Certain button combinations are not possible

### ISSUE THREAD

**Issue by commandcontrolQ** [melonDS-emu/melonDS#2068]
This issue affects every single button, including the D-Pad.
Certain held button combinations cause melonDS to ignore any other button input.

For example:
- Holding both L and R, the Y and A face buttons will not register
- Holding L, R, X and any other face button, all other buttons will not register

There are a large amount of these combinations, which I cannot document in one issue.

To test this out, there is a homebrew DS ROM called 'Diagnose': you can download the ROM [here](https://github.com/user-attachments/files/15847708/DiagnoSe.zip), just make sure that melonDS is set to boot directly into the ROM, otherwise it will not launch.

**Comment by nadiaholmquist** [comment]
This is probably a problem with your keyboard, a lot of them can only register a limited number of keys at once usually ranging from 2 to 6 depending on which specific keys you're pressing.

**Comment by commandcontrolQ** [comment]
You are right, it is a keyboard issue.
