### ISSUE TITLE
The Sims 2 (EUR): Wavely heat effect isn't render properly in OpenGL renderer

### ISSUE THREAD

**Issue by RafaelTrepaUnCarballo** [melonDS-emu/melonDS#2072]
In the desert, the visuals are supposedly distort horizontally on waves.
Software mode shows this effect, but both OpenGL renders don't, moving the whole frame a few pixels left and right instead.
Also, OpenGL (Compute shaders) corrupts the image at x10 resolution and beyond.

Game: 0162 - Sims 2, The (Europe) (En,Fr,De,Es,It) (EUR)
MD5: 676E829FA7AAF658C4DF2046E985730F

Tested on: 

- Windows 10 x64 (Ryzen 7 4800H, GTX2060): Melon 0.9.5 (win64), [melonDS Git (2024/06/16)](https://www.emucr.com/2024/06/melonds-git-20240616.html) (win64). 

**Save:**
[0162 - Sims 2, The (Europe) (En,Fr,De,Es,It).zip](https://github.com/user-attachments/files/15883481/0162.-.Sims.2.The.Europe.En.Fr.De.Es.It.zip)

**Comment by Arisotura** [comment]
sounds like there's some midframe effect going on that OpenGL isn't emulating right
