### ISSUE TITLE
[Regression/Windows] Launching MelonDS with the fullscreen parameter doesn't do anything

### ISSUE THREAD

**Issue by Immersion95** [melonDS-emu/melonDS#2083]
Launching MelonDS with the fullscreen parameter (-f or --fullscreen) doesn't do anything.

It remembers the last state (fullscreen or windowed). If it's fullscreen, the bar is still here. You have to change to windowed then to fullscreen.

Last working commit is https://github.com/melonDS-emu/melonDS/commit/8e9b88d01da0d21c3c35db051d7e44d8ee0c7715

**Comment by Blackbird88** [comment]
Also on windows, but for me it doesn't work at all, melonDS just stays in its default small window state

**Comment by Immersion95** [comment]
Is there any news on this matter or a workaround ?

**Comment by Immersion95** [comment]
Edited the first post and title. The fullscreen parameter doesn't work at all.

**Comment by RSDuck** [comment]
looks like it was forgotten to be readded during refactoring

**Comment by Blackbird88** [comment]
Works for me, unrelated to the issue, but it would be nice if the fullscreen was temporary. Right now exiting melonDS makes it FS on next launch kinda defeating the purpose.

**Comment by RSDuck** [comment]
that should not be the case, we don't store the fullstate state anywhere. Either QT or the OS seems to be storing this. I'll try to override this.

**Comment by RSDuck** [comment]
it actually was our fault. Well I fixed it now though.
