### ISSUE TITLE
melonDS crashes if installed from snap

### ISSUE THREAD

**Issue by Maski190** [melonDS-emu/melonDS#2098]
I installed melonDS using snap on Ubuntu 24.04 but it crashed when I tried to run it. Building from source fixed the problem.

The error was similar to [https://github.com/visualboyadvance-m/visualboyadvance-m/issues/1315](this one), which I solved the same way.

**Comment by RSDuck** [comment]
which snap?

**Comment by Maski190** [comment]
stable 0.9.4

**Comment by nadiaholmquist** [comment]
That's both outdated and unofficial. Consider using [the flatpak](https://flathub.org/apps/net.kuribo64.melonDS) or the build from the website.

**Comment by Maski190** [comment]
Thank you, the .exe from the website seems to work with wine.
