### ISSUE TITLE
Opening game that supports Wi-Fi creates `wfcsettings.bin` in `$HOME` directory

### ISSUE THREAD

**Issue by SuperSamus** [melonDS-emu/melonDS#2100]
In past versions of melonDS, `wfcsettings.bin` used to be created in melonDS's config directory, but it's now created in `$HOME`.
(If melonDS is launched through the terminal instead, the file will be created in `$PWD` instead.)

**Comment by Arisotura** [comment]
is this happening in the 0.9.5 release, or in nightly builds?

**Comment by nadiaholmquist** [comment]
Try https://github.com/melonDS-emu/melonDS/compare/4b17de7e8cd5...5eadd67df6da

**Comment by SuperSamus** [comment]
Fixes the issue! :thumbsup:
