### ISSUE TITLE
Saving fails

### ISSUE THREAD

**Issue by Templayer** [melonDS-emu/melonDS#2113]
Using the nightly build.

Writing a save state fails if the path contains unicode symbols, like diacritics.

Unfortunately, for Czech, pretty much everything has diacritics.

Saving here fails:
V:\Melon DS emulátor\SAVY

Saving here succeeds:
V:\

Workaround: I made symbolic links to fix the issue and set them as default folders. It worked. :)

**Comment by RSDuck** [comment]
https://github.com/melonDS-emu/melonDS/blob/master/src/frontend/qt_sdl/EmuInstance.cpp#L555
and https://github.com/melonDS-emu/melonDS/blob/master/src/frontend/qt_sdl/EmuInstance.cpp#L629

are probably the culprit.

**Comment by RSDuck** [comment]
can you please checkout https://github.com/melonDS-emu/melonDS/commit/12563fb636f27b2eaa6b2a25342bed6ca9268bb0

**Comment by Templayer** [comment]
> can you please checkout [12563fb](https://github.com/melonDS-emu/melonDS/commit/12563fb636f27b2eaa6b2a25342bed6ca9268bb0) ?

Is that / will that be a part of the nightly builds? I'm too lazy to build the application myself. (my time is already predefined this week, I'm afraid :) )

**Comment by RSDuck** [comment]
Every commit made to the master branch (including this one) should be build by the CI (sometimes it skips some if multiple things are commited at once but you get the idea).

**Comment by Templayer** [comment]
> Every commit made to the master branch (including this one) should be build by the CI (sometimes it skips some if multiple things are commited at once but you get the idea).

I tested it and it works. But I found a different issue. I'll make a standalone Issue for it.
