### ISSUE TITLE
Unable to compile on Fedora 40 because of missing qplatformnativeinterface.h

### ISSUE THREAD

**Issue by efeme4** [melonDS-emu/melonDS#2121]
MelonDS fails to compile on Fedora 40 with the following error output

~/melonDS master ⇣3 ❯ cmake --build build
[  7%] Built target teakra
[ 46%] Built target core
[ 46%] Built target slirp_autogen_timestamp_deps
[ 46%] Built target slirp_autogen
[ 67%] Built target slirp
[ 67%] Built target net-utils_autogen_timestamp_deps
[ 68%] Built target net-utils_autogen
[ 72%] Built target net-utils
[ 72%] Built target melonDS_autogen_timestamp_deps
[ 73%] Built target melonDS_autogen
[ 74%] Building CXX object src/frontend/qt_sdl/CMakeFiles/melonDS.dir/main.cpp.o
/home/efeme/melonDS/src/frontend/qt_sdl/main.cpp:50:10: error fatal: qpa/qplatformnativeinterface.h: No existe el fichero o el directorio
   50 | #include <qpa/qplatformnativeinterface.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilación terminada.
gmake[2]: *** [src/frontend/qt_sdl/CMakeFiles/melonDS.dir/build.make:123: src/frontend/qt_sdl/CMakeFiles/melonDS.dir/main.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:289: src/frontend/qt_sdl/CMakeFiles/melonDS.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2

I have all of the qt devel dependencies installed but it fails in any case.

**Comment by efeme4** [comment]
Sorry, one library was actually missing

**Comment by schumischumi** [comment]
For everyone wondering:
For fedora 41 with QT 6 the package is qt6-qtbase-private-devel
