### ISSUE TITLE
Nighly builds crash on boot if only DSi-mode is configured and the console type is set to DSi

### ISSUE THREAD

**Issue by edo9300** [melonDS-emu/melonDS#2141]
As title says, if you enable dsi mode, and don't have DS-mode configured (with its bios and firmware), the emulator will simply always crash on startup the moment you reopen it after saving those settings, if you try to instead boot the firmware manually after configuring DSi-mode, still without DS-mode configured, you'll get the "this firmware is not bootable error". (Nevertheless to say that in the latest official release, the emulator works as intended even without the DS-mode bios being present.

**Comment by Arisotura** [comment]
> As title says, if you enable dsi mode, and don't have DS-mode configured (with its bios and firmware), the emulator will simply always crash on startup the moment you reopen it after saving those settings

can't reproduce that part, can you provide more info?

however, I can reproduce the other part, DSi mode shits itself when not using external DS BIOS/firmware

**Comment by edo9300** [comment]
> > As title says, if you enable dsi mode, and don't have DS-mode configured (with its bios and firmware), the emulator will simply always crash on startup the moment you reopen it after saving those settings
> 
> can't reproduce that part, can you provide more info?
> 
> however, I can reproduce the other part, DSi mode shits itself when not using external DS BIOS/firmware

Just tested, seems that the crash on startup got fixed by prior commits (when i attempted to debug it, it was caused by melon trying to signal a thread about the firmware not being bootable but that thread wasn't runnning yet)
