### ISSUE TITLE
ARM7 and ARM9 debugger doesn't work at all:

### ISSUE THREAD

**Issue by micsthepick** [melonDS-emu/melonDS#2147]
This line is outdated:

https://github.com/melonDS-emu/melonDS/blob/4f6498c99c5dcdb780371fe936d49e32df148e6e/src/frontend/qt_sdl/EmuSettingsDialog.cpp#L98

Needs to take into account instance number?

see also:
#2144 
I believe that this is the main cause.

**Comment by micsthepick** [comment]
... scratch that, I didn't notice that it's using instcfg instead of cfg.

**Comment by micsthepick** [comment]
https://github.com/melonDS-emu/melonDS/blame/4f6498c99c5dcdb780371fe936d49e32df148e6e/src/Args.h#L122-L125

Not sure if this should always be nullopt...

**Comment by Arisotura** [comment]
yeah, the gdb stuff needs some fixing and reworking. this is weird

**Comment by Ukalus** [comment]
i ran into this too, is there a workaround?

**Comment by RSDuck** [comment]
https://github.com/melonDS-emu/melonDS/commit/74f479ce6d956375f9bf9d2c3fd0b0b7a6f4ad56 fixed this particular issue.

Though it looks like there is a race condition in the GDB protocol which I haven't figured completely out how to fix.

**Comment by RSDuck** [comment]
https://github.com/melonDS-emu/melonDS/commit/a3d696121e8d0643bbe45d6bdecdb99e2d62cbe1 should have hopefully done the rest.

If you are still experiencing issues (besides the known one of gdb stub settings not being reflected properly until a restart) please let me know.
