### ISSUE TITLE
melonDS (Android) does not recognize Xbox Series controller's triggers

### ISSUE THREAD

**Issue by RazzeeX** [melonDS-emu/melonDS#2148]
Hi.

I have my smartphone mounted to an Xbox Series controller through an USB Type-C to USB Type-C cable.

All buttons work, except for the triggers (LT, RT) that cannot be mapped.

Is there a workaround?

**Comment by sudoBash418** [comment]
Wrong project (you're probably looking for https://github.com/rafaelvcaetano/melonDS-android)

**Comment by RazzeeX** [comment]
Damn, my bad. I will close this (and reopen if the same issue affects the PC version).
