### ISSUE TITLE
Action Replay cheats seemingly not working on one computer but working on another with the same ROM and same emulator version

### ISSUE THREAD

**Issue by BromBromBromley** [melonDS-emu/melonDS#2163]
As the title says, for some reason, on my computer with Windows 11, an Action Replay cheat that I use for walking through "walls" in Pokémon Black 2 doesn't work for no discernible reason. The code in question is here:
94000130 FDFF0000
A4000130 FFFC0003
DA000000 04000130
D7000000 02000DFE
D2000000 00000000
5219BCBC D0002901
1219BCC0 00002004
92000DFE FFFC0002
1219BCC0 00002002
D2000000 00000000
In order to enable it, L + A must be pressed, but even when double and triple checking my hotkeys were set correctly, that cheats were enabled, that the code was the same between this machine and my Windows 10 machine, that the ROM was the same between machines, and that I was even pressing the correct keys, for some reason, only on this computer do I have issues with the code not enabling. As for where I found the AR code, it unfortunately is just from a GameFAQs post being post #226 on [this page](https://gamefaqs.gamespot.com/boards/661226-pokemon-black-version-2/64261559?page=22). Any help would be greatly appreciated!

**Comment by RSDuck** [comment]
It could be some really nasty issue inside melonDS. Though just to be sure, you aren't using the same keyboard on both computers? Some keyboards have trouble detecting nearby keys being pressed at the same time.

**Comment by BromBromBromley** [comment]
The keyboards are different, yes, but other ley combinations that are similar _do_ work.

**Comment by BromBromBromley** [comment]
It seems this is still an issue on the 1.0 RC as well. Is there anything that I could do to help in diagnosing the issue?

**Comment by BromBromBromley** [comment]
Somehow even using the same cheat code between PCs, it wasn't happy until I gave it another cheat code that seemed to target a different memory address even though the same ROM was being used on both.
