### ISSUE TITLE
Can't connect with another via wifi on pokemon bw/bw2

### ISSUE THREAD

**Issue by Mrthomas20121** [melonDS-emu/melonDS#2164]
i'm trying to play against another player in bw/bw2, we're both playing on emulator(melonDS) and yet we're stuck in connecting.
(we still have the music playing in the background and have the spinning animations next to connecting)

it works with a ds and an emulator but not both emulator, is there any ways we can fix this?

I don't believe this is on Poké classic network/wiimfi end because it works if one of us uses a ds, so something must be blocking it

**Comment by RSDuck** [comment]
Are you each using the firmware of your DS?

**Comment by Mrthomas20121** [comment]
I do not know about them but for my part, I am not using the default firmware

**Comment by Mrthomas20121** [comment]
I resetted to the default firmware, we'll see if it works when we next try wifi

**Comment by mwnDK1402** [comment]
I'm actually trying to do the exact same thing.

MelonDS version: 0.9.5
Console type: DS
DS-mode: default firmware (external unchecked)

The two devices can ping each other and have no issues connecting. I've been trying to test this by joining the Union Room, and it works with two instances on the same device, but not between two devices running the emulator.
