### ISSUE TITLE
Picross 3D - Missing lines between blocks when using OpenGL

### ISSUE THREAD

**Issue by bslenul** [melonDS-emu/melonDS#2165]
Hey!

I noticed that when playing Picross 3D the white lines between blocks don't appear with OpenGL (even at 1x), making the game very hard to play because it becomes very hard to count blocks:
* SW:
  ![image](https://github.com/user-attachments/assets/9036d9c0-2b6a-4cb3-a0be-7940437b0b3d)
* OpenGL:
  ![image](https://github.com/user-attachments/assets/de0bbe63-3641-49c5-bf73-8b37304ff14f)

I don't really mind using SW but still wanted to filed an issue about it in case it could be fixed.

melonDS 0.9.5 / Windows 10 / i5-12400F / RTX 3060 Ti

I also noticed the numbers are "twitching" (SW and GL) but idk if it's a bug or not, I'll try testing on real HW later:

https://github.com/user-attachments/assets/08df782d-6d71-44ca-8ebe-c02212b5f8bd

**Comment by bslenul** [comment]
Oh nvm, the lines appear when selecting the "OpenGL (Compute shader)" setting which didn't exist in the 0.9.5 version I was using (from the website). It looks fine up to 2x!

Closing, and sorry for the waste of time :x

**Comment by TheRealWario** [comment]
You didn’t waste anyone’s time. All you were doing is trying to investigate an issue you weren’t aware was fixed since the latest full release. What matters is we know what the problem was and that you found a fix. Just be sure to check your issues between versions before you create an issue.

**Comment by ljorg** [comment]
Thank you for this! Now I can enjoy this classic to the fullest again!
