### ISSUE TITLE
Screen Layout: Swap Screens causes a CTD when checked

### ISSUE THREAD

**Issue by AcerUp** [melonDS-emu/melonDS#2175]
The newest Melon DS builds since the past week cause a CTD when Screen Layout: Swap Screens is checked/selected on initial launch of the executable. It occurs within seconds upon initially launching MelonDS.exe, but the CTD is delayed if:

-the menu options are currently being navigated through
 or 
-if a game is currently running.

The CTD ceases if Screen Layout: Swap Screens is unchecked upon launching MelonDS.exe

PC specifications:  
AMD Ryzen 9 7950x 
Gigabyte 4090 
Windows 11 pro 24H2 os 26100.2161
Aorus elite x670 ax (Bios F31)
128 gb ddr5 G.SKILL Trident Z5 Neo RGB Series (AMD Expo)

**Comment by RSDuck** [comment]
What does CTD mean?

**Comment by AcerUp** [comment]
CTD: Crash to Desktop. The program crashes and closes near instantly without affecting the rest of the computer.

**Comment by AcerUp** [comment]
This has been resolved as of the latest commit. Well done.
