### ISSUE TITLE
error compiling on OpenSUSE TW

### ISSUE THREAD

**Issue by petran79** [melonDS-emu/melonDS#2180]
I tried locating the exact names of the required libraries but it seems something is missing regarding QT5 development. Any idea which library is missing for Tumbleweed?

[ 76%] Building CXX object src/frontend/qt_sdl/CMakeFiles/melonDS.dir/EmuInstance.cpp.o
[ 77%] Building CXX object src/frontend/qt_sdl/CMakeFiles/melonDS.dir/EmuThread.cpp.o
[ 76%] Building CXX object src/frontend/qt_sdl/CMakeFiles/melonDS.dir/EmuInstanceAudio.cpp.o
/home/petros/Downloads/melonDS-master/melonDS-master/src/frontend/qt_sdl/Screen.cpp:28:10: fatal error: qpa/qplatformnativeinterface.h: No such file or directory
   28 | #include <qpa/qplatformnativeinterface.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
/home/petros/Downloads/melonDS-master/melonDS-master/src/frontend/qt_sdl/Window.cpp:50:10: fatal error: qpa/qplatformnativeinterface.h: No such file or directory
   50 | #include <qpa/qplatformnativeinterface.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
gmake[2]: *** [src/frontend/qt_sdl/CMakeFiles/melonDS.dir/build.make:140: src/frontend/qt_sdl/CMakeFiles/melonDS.dir/Screen.cpp.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
gmake[2]: *** [src/frontend/qt_sdl/CMakeFiles/melonDS.dir/build.make:154: src/frontend/qt_sdl/CMakeFiles/melonDS.dir/Window.cpp.o] Error 1
/home/petros/Downloads/melonDS-master/melonDS-master/src/frontend/qt_sdl/main.cpp:46:10: fatal error: qpa/qplatformnativeinterface.h: No such file or directory
   46 | #include <qpa/qplatformnativeinterface.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
gmake[2]: *** [src/frontend/qt_sdl/CMakeFiles/melonDS.dir/build.make:126: src/frontend/qt_sdl/CMakeFiles/melonDS.dir/main.cpp.o] Error 1
/home/petros/Downloads/melonDS-master/melonDS-master/src/frontend/qt_sdl/EmuInstance.cpp: In destructor ‘EmuInstance::~EmuInstance()’:
/home/petros/Downloads/melonDS-master/melonDS-master/src/frontend/qt_sdl/EmuInstance.cpp:168:10: warning: ‘melonDS::NDS::Current’ is deprecated: Temporary workaround until JIT code generation is revised to accommodate multiple NDS objects. [-Wdeprecated-declarations]
  168 |     NDS::Current = nullptr;
      |          ^~~~~~~
In file included from /home/petros/Downloads/melonDS-master/melonDS-master/src/frontend/qt_sdl/EmuInstance.h:25,
                 from /home/petros/Downloads/melonDS-master/melonDS-master/src/frontend/qt_sdl/EmuInstance.cpp:38:
/home/petros/Downloads/melonDS-master/melonDS-master/src/frontend/qt_sdl/../../NDS.h:540:130: note: declared here
  540 |     [[deprecated("Temporary workaround until JIT code generation is revised to accommodate multiple NDS objects.")]] static NDS* Current;
      |                                                                                                                                  ^~~~~~~
/home/petros/Downloads/melonDS-master/melonDS-master/src/frontend/qt_sdl/EmuInstance.cpp:168:10: warning: ‘melonDS::NDS::Current’ is deprecated: Temporary workaround until JIT code generation is revised to accommodate multiple NDS objects. [-Wdeprecated-declarations]
  168 |     NDS::Current = nullptr;
      |          ^~~~~~~
/home/petros/Downloads/melonDS-master/melonDS-master/src/frontend/qt_sdl/../../NDS.h:540:130: note: declared here
  540 |     [[deprecated("Temporary workaround until JIT code generation is revised to accommodate multiple NDS objects.")]] static NDS* Current;
      |                                                                                                                                  ^~~~~~~
/home/petros/Downloads/melonDS-master/melonDS-master/src/frontend/qt_sdl/EmuInstance.cpp: In member function ‘bool EmuInstance::updateConsole(UpdateConsoleNDSArgs&&, UpdateConsoleGBAArgs&&)’:
/home/petros/Downloads/melonDS-master/melonDS-master/src/frontend/qt_sdl/EmuInstance.cpp:1345:14: warning: ‘melonDS::NDS::Current’ is deprecated: Temporary workaround until JIT code generation is revised to accommodate multiple NDS objects. [-Wdeprecated-declarations]
 1345 |         NDS::Current = nullptr;
      |              ^~~~~~~
/home/petros/Downloads/melonDS-master/melonDS-master/src/frontend/qt_sdl/../../NDS.h:540:130: note: declared here
  540 |     [[deprecated("Temporary workaround until JIT code generation is revised to accommodate multiple NDS objects.")]] static NDS* Current;
      |                                                                                                                                  ^~~~~~~
/home/petros/Downloads/melonDS-master/melonDS-master/src/frontend/qt_sdl/EmuInstance.cpp:1345:14: warning: ‘melonDS::NDS::Current’ is deprecated: Temporary workaround until JIT code generation is revised to accommodate multiple NDS objects. [-Wdeprecated-declarations]
 1345 |         NDS::Current = nullptr;
      |              ^~~~~~~
/home/petros/Downloads/melonDS-master/melonDS-master/src/frontend/qt_sdl/../../NDS.h:540:130: note: declared here
  540 |     [[deprecated("Temporary workaround until JIT code generation is revised to accommodate multiple NDS objects.")]] static NDS* Current;
      |                                                                                                                                  ^~~~~~~
/home/petros/Downloads/melonDS-master/melonDS-master/src/frontend/qt_sdl/EmuInstance.cpp:1357:14: warning: ‘melonDS::NDS::Current’ is deprecated: Temporary workaround until JIT code generation is revised to accommodate multiple NDS objects. [-Wdeprecated-declarations]
 1357 |         NDS::Current = nds;
      |              ^~~~~~~
/home/petros/Downloads/melonDS-master/melonDS-master/src/frontend/qt_sdl/../../NDS.h:540:130: note: declared here
  540 |     [[deprecated("Temporary workaround until JIT code generation is revised to accommodate multiple NDS objects.")]] static NDS* Current;
      |                                                                                                                                  ^~~~~~~
/home/petros/Downloads/melonDS-master/melonDS-master/src/frontend/qt_sdl/EmuInstance.cpp:1357:14: warning: ‘melonDS::NDS::Current’ is deprecated: Temporary workaround until JIT code generation is revised to accommodate multiple NDS objects. [-Wdeprecated-declarations]
 1357 |         NDS::Current = nds;
      |              ^~~~~~~
/home/petros/Downloads/melonDS-master/melonDS-master/src/frontend/qt_sdl/../../NDS.h:540:130: note: declared here
  540 |     [[deprecated("Temporary workaround until JIT code generation is revised to accommodate multiple NDS objects.")]] static NDS* Current;
      |                                                                                                                                  ^~~~~~~
gmake[1]: *** [CMakeFiles/Makefile2:289: src/frontend/qt_sdl/CMakeFiles/melonDS.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2

**Comment by RSDuck** [comment]
The QT native platform package seems to be missing, not sure what it is called on OpenSUSE.

**Comment by petran79** [comment]
I installed the whole qt5_devel package and qt creator and I still get this error. 
also : 
'libqt5-qtbase' not found in package names. Trying capabilities.
'libQt5Core5' providing 'libqt5-qtbase' is already installed.

Though first command performs with no issues.
cmake -B build
-- The C compiler identification is GNU 14.2.1
-- The CXX compiler identification is GNU 14.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Enabling GDB stub
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Looking for shm_open in rt
-- Looking for shm_open in rt - found
-- Found PkgConfig: /usr/bin/pkg-config (found version "2.2.0")
-- Checking for module 'sdl2'
--   Found sdl2, version 2.30.8
-- Checking for module 'libarchive'
--   Found libarchive, version 3.7.6
-- Checking for module 'libzstd'
--   Found libzstd, version 1.5.6
-- Checking for module 'libenet'
--   Found libenet, version 1.3.18
-- Found X11: /usr/include
-- Looking for XOpenDisplay in /usr/lib64/libX11.so;/usr/lib64/libXext.so
-- Looking for XOpenDisplay in /usr/lib64/libX11.so;/usr/lib64/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Performing Test HAVE_EGL
-- Performing Test HAVE_EGL - Success
-- Found EGL: /usr/include (found version "1.5")
-- Found Wayland_Client: /usr/lib64/libwayland-client.so (found version "1.23.1")
-- Found Wayland: /usr/lib64/libwayland-client.so (found version "1.23.1") found components: Client
-- Configuring done (2.0s)
-- Generating done (0.1s)
-- Build files have been written to: /home/petros/Downloads/melonDS-master/melonDS-master/build

**Comment by RSDuck** [comment]
QPA is usually a separate package. It is usually part of something called QT private. E.g. qt6-qtbase-private-devel.x86_64 on Fedora or qtbase5-private-dev on Ubuntu.

**Comment by RSDuck** [comment]
Is it possible that you installed QT 6 private, but compile with QT 5?

**Comment by petran79** [comment]
I only use cmake -B build and  cmake --build build -j$(nproc --all)
I have not touched any compilation parameters. Do I need to modify anything?

**Comment by RSDuck** [comment]
melonDS currently defaults to QT5, so you need to install qt5 private.

**Comment by petran79** [comment]
Now it seems this was the issue
sudo zypper in libqt5-qtbase-private-headers-devel
Refreshing service 'NVIDIA'.
Refreshing service 'openSUSE'.
Loading repository data...
Reading installed packages...
Resolving package dependencies...

The following 14 NEW packages are going to be installed:
  libQt5Core-private-headers-devel libQt5DBus-private-headers-devel libQt5Gui-private-headers-devel
  libQt5KmsSupport-devel-static libQt5KmsSupport-private-headers-devel
  libQt5Network-private-headers-devel libQt5OpenGL-private-headers-devel
  libQt5PlatformSupport-devel-static libQt5PlatformSupport-private-headers-devel
  libQt5PrintSupport-private-headers-devel libqt5-qtbase-private-headers-devel
  libQt5Sql-private-headers-devel libQt5Test-private-headers-devel libQt5Widgets-priva

but now compilation stucks at 90 percent with message

 90%] Building C object src/frontend/qt_sdl/CMakeFiles/melonDS.dir/__/glad/glad.c.o
[ 90%] Building CXX object src/frontend/qt_sdl/CMakeFiles/melonDS.dir/__/duckstation/gl/context.cpp.o
In file included from /home/petros/Downloads/melonDS-master/melonDS-master/src/frontend/duckstation/gl/context.cpp:15:
/home/petros/Downloads/melonDS-master/melonDS-master/src/frontend/duckstation/gl/context_egl_wayland.h:3:10: fatal error: wayland-egl.h: No such file or directory
    3 | #include <wayland-egl.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
gmake[2]: *** [src/frontend/qt_sdl/CMakeFiles/melonDS.dir/build.make:560: src/frontend/qt_sdl/CMakeFiles/melonDS.dir/__/duckstation/gl/context.cpp.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
gmake[1]: *** [CMakeFiles/Makefile2:289: src/frontend/qt_sdl/CMakeFiles/melonDS.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2

**Comment by RSDuck** [comment]
you probably also need to install some wayland dev package.

**Comment by petran79** [comment]
I found this. had to add on cmakelist the following
include_directories("/usr/include/wayland")
Then it compiled normally.
 https://github.com/melonDS-emu/melonDS/issues/1555
