### ISSUE TITLE
I NEED THE DOWNLOAD

### ISSUE THREAD

**Issue by WHATCANIDODODODO** [melonDS-emu/melonDS#2184]
No offense, but I want to download the latest app. Btw, I'm on my phone. Can I get the link, please? Thank you, if yes.

**Comment by WumpusFruit** [comment]
I think you can download from the app store, or RetroArch. What OS are you using? iOS or Android?

**Comment by RSDuck** [comment]
There are unofficial ports, but we don't support Android or iOS.
