### ISSUE TITLE
Why has there been so long since the last release?

### ISSUE THREAD

**Issue by BlurrySquire** [melonDS-emu/melonDS#2193]
I'm guessing this is because the milestones in the roadmap haven't been reached yet but I was just curious as to why we are left with a 2 years old build.

**Comment by BlurrySquire** [comment]
My bad didn't notice the new post on the website.

**Comment by Arisotura** [comment]
we've done a lot of work, and the main developer (me) has ADHD

there are other reasons too, it's complicated...
