### ISSUE TITLE
Cannot build emulator

### ISSUE THREAD

**Issue by CodaWear** [melonDS-emu/melonDS#2209]
Heres my output

FAILED: src/CMakeFiles/core.dir/ARMJIT_Memory.cpp.obj
C:\msys64\mingw64\bin\c++.exe -DARCHITECTURE_x86_64=1 -DGDBSTUB_ENABLED -DJIT_ENABLED -DMELONDS_GL_HEADER=\"frontend/glad/glad.h\" -DNOMINMAX -DOGLRENDERER_ENABLED -DWIN32_LEAN_AND_MEAN -IC:/msys64/home/Coda/melonDS/build/src -IC:/msys64/home/Coda/melonDS/src/teakra/src/../include -O3 -DNDEBUG -std=gnu++17 -flto=auto -fno-fat-lto-objects -fwrapv -Wno-invalid-offsetof -MD -MT src/CMakeFiles/core.dir/ARMJIT_Memory.cpp.obj -MF src\CMakeFiles\core.dir\ARMJIT_Memory.cpp.obj.d -o src/CMakeFiles/core.dir/ARMJIT_Memory.cpp.obj -c C:/msys64/home/Coda/melonDS/src/ARMJIT_Memory.cpp
C:/msys64/home/Coda/melonDS/src/ARMJIT_Memory.cpp: In member function 'bool melonDS::ARMJIT_Memory::UnmapFromRange(melonDS::u32, melonDS::u32, melonDS::u32, melonDS::u32)':
C:/msys64/home/Coda/melonDS/src/ARMJIT_Memory.cpp:350:10: error: 'UnmapViewOfFileEx' was not declared in this scope; did you mean 'UnmapViewOfFile2'?
  350 |     if (!UnmapViewOfFileEx(dst, MEM_PRESERVE_PLACEHOLDER))
      |             ^~~~~~~~~~~~~~~~~
      |              UnmapViewOfFile2
C:/msys64/home/Coda/melonDS/src/ARMJIT_Memory.cpp: In destructor 'melonDS::ARMJIT_Memory::~ARMJIT_Memory()':
C:/msys64/home/Coda/melonDS/src/ARMJIT_Memory.cpp:944:33: error: 'UnmapViewOfFileEx' was not declared in this scope; did you mean 'UnmapViewOfFile2'?
  944 |             bool viewUnmapped = UnmapViewOfFileEx(MemoryBase, MEM_PRESERVE_PLACEHOLDER);
      |                                                      ^~~~~~~~~~~~~~~~~
      |                                                      UnmapViewOfFile2

**Comment by CodaWear** [comment]
I'm on windows 11 should I use 7?

**Comment by RSDuck** [comment]
no, I noticed that this function seems to be introduced in Windows 8.

If you aren't already, try building via ucrt instead of mingw64 and try updating packages (`pacman -Syu`).
