### ISSUE TITLE
(melonDS 1.0 RC) Lid closing will crash the emulator.

### ISSUE THREAD

**Issue by ASlayer9** [melonDS-emu/melonDS#2210]
When testing the new split window feature, tried using the close lid function. Emulator would stop, as usual, but would crash shortly after. Reverted to a one screen with both windows and closed the lid again. The emulator crashed again.

**Comment by AssaultEngineer** [comment]
I am having this issue as well, using the lid open\close hotkey results in melonds either closing for some reason or straight up crash.

**Comment by SlawekNowy** [comment]
Seems to be fixed in master.

**Comment by KostaSaizo7** [comment]
> Seems to be fixed in master.

I confirm this

**Comment by ASlayer9** [comment]
@SlawekNowy @KostaSaizo7 Tried building from source with MSYS2 on a windows x64, Static and Dynamic, and keep getting nowhere. Static keeps throwing failures at src/frontend/qt_sdl/CMakeFiles/melonDS.dir/EmuInstance.cpp.obj when compiling. For Dynamic, even with the DLLs it will not load the program, I get "application was unable to start correctly (0x000007b). Any help would be appreciated.

**Comment by ASlayer9** [comment]
Issue fixed with current master build.
