### ISSUE TITLE
are there plans for scanline filters to melonds?

### ISSUE THREAD

**Issue by DaStar22** [melonDS-emu/melonDS#2217]
recently i started enjoying scanline filters on emulators and i wish it would be added to the plans of the future.

sending love.

ps: i couldn't poste this on requests and somehow i posted it here sorry.

**Comment by DaStar22** [comment]
so i downloaded retroarch... tried it... didn't like it... i was yearning for something i found on pizzaboyGBA... maybe because i tried it on windows, too meny pixels? anyways, thanx you so much for replying.

**Comment by DaStar22** [comment]
> It would be cool if MelonDS would integrate Librashader: https://github.com/SnowflakePowered/librashader

i mean at this point all emulators have filters option... maybe MDS devs are focusing on accuracy for the moment (the new OpenGL is amazing and far better on the 1.0 release) and it will be implemented in the future? hard to say...

**Comment by DaStar22** [comment]
> Librashader says it supports various versions of OpenGL, and its sort-of a plug-and-play solution, in that you dont have to develop the shaders or whatever, just get it hooked into the rendering and it does the rest for you. And the dev of Librashader is very willing to help people out who run into issues in integrating it into their emulators. So hopefully that makes it a low enough barrier that someone will look into it. ![afbeelding](https://private-user-images.githubusercontent.com/124319511/389828188-6dbcc116-9d28-437c-bc91-88e3f026ba1d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2MDQ1OTEsIm5iZiI6MTczMjYwNDI5MSwicGF0aCI6Ii8xMjQzMTk1MTEvMzg5ODI4MTg4LTZkYmNjMTE2LTlkMjgtNDM3Yy1iYzkxLTg4ZTNmMDI2YmExZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNlQwNjU4MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZWMxYjRiODI0Nzk4NTAyMjhmMjBkMWE4ZDAzZTZlMmQyZDE5MDNjNmExMThkMmE0NTRjZTE0YjQzMzRhOTYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.UA1R7NuRKfBfJsXIe2lR9pO4dKN7Y-Edzj7oLV2BlRw)

VERY interesting... thank you for explaining.

**Comment by SnowSquire** [comment]
you can use reshade with melonds in the meantiem

**Comment by DaStar22** [comment]
> you can use reshade with melonds in the meantime



> Reshade can totally do some basic scanline filter, so that should be a decent solution for @DaStar22 's question.
> 
> I would love to have some good color correction to emulate the NDS' LCD-screen more accurately though, and sadly the NDS-Color.slang/glsl shader isnt available on Reshade.

thank you all this was what i needed!

**Comment by Pedro-HDSR** [comment]
## I made a fork specifically for this:

_https://github.com/Pedro-HDSR/melonDS/tree/feature/frontend-modern-filters_

It adds libretro slang shaders support directly in the melonDS UI.

I also made a pull request 'pr-slang-shaders' to be discussed and possibly added to the master branch in the future.


### A few examples:

<img width="308" height="303" alt="Image" src="https://github.com/user-attachments/assets/515dfbd5-f97b-4d4a-b3d0-aaec0228757c" />

<img width="706" height="548" alt="Image" src="https://github.com/user-attachments/assets/eaa47b9c-cfa8-4d0e-bf94-c4164afac171" />

<img width="1840" height="1380" alt="Image" src="https://github.com/user-attachments/assets/c011ee56-3bdf-4e8b-933b-fbfe1e3d7a9d" />

<img width="1840" height="1380" alt="Image" src="https://github.com/user-attachments/assets/37de2da7-f41b-4c97-8f4b-092010fa282b" />

<img width="1840" height="1380" alt="Image" src="https://github.com/user-attachments/assets/95129191-766c-4554-be98-54d4929e39ba" />

<img width="1840" height="1380" alt="Image" src="https://github.com/user-attachments/assets/40856707-19c8-4834-977f-3055289ed702" />

<img width="1840" height="1380" alt="Image" src="https://github.com/user-attachments/assets/4a503d63-9c93-4142-92e8-00e4b1587efb" />
