### ISSUE TITLE
1.0 RC on Flatpak/Flathub

### ISSUE THREAD

**Issue by SHRMP0** [melonDS-emu/melonDS#2223]
Sorry if this is not the right place to ask, but is there an estimate for when the Flatpak release will be updated to 1.0 RC on [Flathub](https://flathub.org/apps/net.kuribo64.melonDS)?

**Comment by nadiaholmquist** [comment]
I actually did all the work for it the other day and then forgot to push it... I'll do that tomorrow.

**Comment by nadiaholmquist** [comment]
Just submitted it, should show up in the flathub beta repo relatively soon.
