### ISSUE TITLE
Pictochat fail

### ISSUE THREAD

**Issue by leptiphoenix** [melonDS-emu/melonDS#223]
-I made 2 folder for 2 ds.
-named first one ds and second one ds2
-run them
-connected ds in room chat a
-connected ds2 in room chat a
-send "1" whit ds
-send "2" whit ds2
There is the result :
![test](https://user-images.githubusercontent.com/35071358/34526387-9ed0ad3e-f0a2-11e7-8d55-3a8d714623ef.jpg)
I don't understand what is going on. Every time I test, the first ds to connect in a room can send messages and the second receive it but the second can send only one message that the first ds doesn't receive and then the send function is blocked.

**Comment by Gamerappa** [comment]
Wireless Emulation isn't fully complete

**Comment by leptiphoenix** [comment]
> Wireless Emulation isn't fully complete
I know, I just want to help dev to find solutions.
But my knowledge in emulation process is really weak. So I only report issues and try to be accurate.

**Comment by StapleButter** [comment]
sometimes client->host transfers fail, which result in this. haven't yet managed to fix it.

**Comment by Arisotura** [comment]
fixed with local_wifi branch
