### ISSUE TITLE
Why doesnt download play work on Mario Party DS

### ISSUE THREAD

**Issue by CrankySupertoonArchive** [melonDS-emu/melonDS#288]
~~I cannot get it to even work. The non download play method of Mario Kart DS Works, but the download play one dosent. Im asking because the game i want to use doesnt support the normal way~~

It works on New Super Mario Bros DS, but not on Mario Party, or Mario kart DS

**Comment by CrankySupertoon01** [comment]
Not trying to bump but im just really curious since i think its a techional thing

**Comment by CindyLouWho03** [comment]
Ahh, what makes game different

**Comment by StapleButter** [comment]
dunno. they probably have different tolerance to transmit errors.

doesn't help that our error handling is wrong, it's basically saying "everything went OK but your reply's not here".
