### ISSUE TITLE
Dragon quest 9 multiplayer on melonds

### ISSUE THREAD

**Issue by Danyaal044** [melonDS-emu/melonDS#397]
So me and my friends were trying to play dq9 together but we couldn't get into the same game. I was hoping someone had a solution on how to get into the each other game. The multiplayer worked when I tried it by myself (2 emulator running on the same computer). Any suggestions on how to get in the same game?

**Comment by mga-py** [comment]
I and connect it to the same pc (different users by remote control) but it is true that the maximum that we have lasted connected is 5 minutes after the connection closes, it can be sometimes 1 minute, other times 3 ... you can not play Then, trying with another computer on the same local network, all the coverage lines appear for a few seconds, but they are removed instantly and connection error occurs.
Please could you improve the Wi-Fi connection even more I think that is what the community wants the most

**Comment by KostaSaizo7** [comment]
Fixed by #1516
![unknown](https://user-images.githubusercontent.com/39852873/192082403-76c6fd3f-113c-41a1-b937-626bf99356ab.png)
