### ISSUE TITLE
Pokemon Black : Relocator not working

### ISSUE THREAD

**Issue by ghost** [melonDS-emu/melonDS#436]
Want to thank you guys for bringing the internet on MelonDS so far..
But recently I used Pokemon Relocator to transport the event pokemon from Heartgold to Black.
Everything works perfectly including using the DS Download Play too..
But at the end when both the games are saving, they keep on saving but even after 30 mins. they are not able to save.

![image](https://user-images.githubusercontent.com/46560550/58850295-8b883580-86ab-11e9-8f80-f3d9304217d5.png)

**Comment by KostaSaizo7** [comment]
Fixed by https://github.com/melonDS-emu/melonDS/pull/1516

![Screenshot 2022-09-24 092336](https://user-images.githubusercontent.com/39852873/192083387-41dc0af0-467d-47f1-8a39-b754375fe042.jpg)
![Screenshot 2022-09-24 092539](https://user-images.githubusercontent.com/39852873/192083393-5cec8695-3229-4f58-9542-011c8de12dd2.jpg)

**Comment by JonatthanVB** [comment]
I'm trying to do the same process at Melonds and I'm not trying success, I've downloaded the DSi firmware bios but when I enter the connection screen between them after they connect with the error… if anyone could explain the step by step how to make it functional or some rar. already configured would help a lot

**Comment by patataofcourse** [comment]
"the error" doesn't help - which error are you getting? can you show screenshots or video footage
also for what it's worth you don't need the DSi mode BIOS, just the original DS ones - but you'll need a functional firmware for that

**Comment by JonatthanVB** [comment]
Okay, thank you very much for your attention and speed, I will make the prints and indicate which errors are occurring

**Comment by JonatthanVB** [comment]
> "the error" doesn't help - which error are you getting? can you show screenshots or video footage also for what it's worth you don't need the DSi mode BIOS, just the original DS ones - but you'll need a functional firmware for that
![Sem título4](https://user-images.githubusercontent.com/25874483/223742378-048bbf84-5b47-4522-8094-356681402896.png)
![Sem título5](https://user-images.githubusercontent.com/25874483/223742391-f3301c8b-ee1b-4663-b93f-c2271e6dbe71.png)
![Sem título6](https://user-images.githubusercontent.com/25874483/223742421-bc45e68e-0e5f-4d88-9a6d-49f3c6bdaf1a.png)

**Comment by patataofcourse** [comment]
what did you do in the second ds, the one with the white screens? it clearly isn't working as it should

**Comment by JonatthanVB** [comment]
after doing this "download" it connects with instance 1 and enters this white screen

**Comment by patataofcourse** [comment]
it may be DSi mode thats causing this to be weird, can you try on DS mode? feel frew to join the discord and i can help you over there

**Comment by JonatthanVB** [comment]
Yes, I'm trying in DSi mode, I've tried countless firmware and nothing yet, in DS mode I haven't tried yet, ok I will join discord, which link? And thank you very much for your attention and education, let's try to correct this failure
