### ISSUE TITLE
Strange behavior in Pokémon, involving "local wireless"

### ISSUE THREAD

**Issue by ghost** [melonDS-emu/melonDS#486]
Sometimes, the local wireless icon with 0 bars of signal shows up in the corner of the screen during battles, which is not supposed to happen.

It only happens rarely, and it goes away if you soft reset (or vice-versa, it can start happening after a soft-reset.)

https://gfycat.com/helplessflippantaardvark

**Comment by Arisotura** [comment]
you sure it doesn't also happen on hardware like if you enable wireless features?

**Comment by Ammako** [comment]
There are no wireless features to enable, unlike Gen. 5. The only times a wireless signal icon should be showing up in battles, is during wireless link battles at the Union Room, or wireless multiplayer co-op at the Battle Tower.

Sometimes, the game doesn't respond to touch input after a soft-reset, until you enter a battle, at which point touch input works once again. As I've just found out, whenever this happens, is also when the game decides to show wireless signal icons in battles.

I've done my share of soft-resetting on hardware, this never happens.

**Comment by Arisotura** [comment]
ok then:

check if the weird behavior persists if you save a savestate from when it occurs, then close/reopen teh emu and load that state

if so, could you send a state where the weird behavior happens and one where it's normal?

so I can figure out what's not being reset correctly

**Comment by Ammako** [comment]
It persists, yes.

[states.zip](https://github.com/Arisotura/melonDS/files/3378260/states.zip)

**Comment by Arisotura** [comment]
I fear there's some emulation bug involved

try on the latest revision?

**Comment by Ammako** [comment]
I can do that, if you can link me a pre-compiled exe.

**Comment by Arisotura** [comment]
http://kuribo64.net/get.php?id=r7X8RkonKE3uHVJc

tell me about it

**Comment by Ammako** [comment]
I was able to reproduce this on there, yes.

**Comment by Arisotura** [comment]
blarg

**Comment by KostaSaizo7** [comment]
Probably fixed by https://github.com/melonDS-emu/melonDS/pull/1516
