### ISSUE TITLE
[OpenGL] Chibi-Robo Park Patrol - Incorrect title screen graphics

### ISSUE THREAD

**Issue by McJ0n** [melonDS-emu/melonDS#525]
Under OpenGL the background of the title screen appears black instead of white, and when it cuts away to various demo scenes the screen is nearly completely white but you can just barely make things out. Software renderer handles things correctly, so it's not a huge problem. Just a curiosity I thought I'd draw attention to.
Below ordering is OGL->SW, OGL->SW

![ogl park patrol title](https://user-images.githubusercontent.com/56448084/66670367-989fcd00-ec27-11e9-9b28-9056764a61ab.png)![sw park patrol title](https://user-images.githubusercontent.com/56448084/66670370-9a699080-ec27-11e9-9a59-5e25bd458e54.png)
![ogl park patrol demo](https://user-images.githubusercontent.com/56448084/66670383-a48b8f00-ec27-11e9-8b48-ca4135b6270c.png)![sw park patrol demo](https://user-images.githubusercontent.com/56448084/66670385-a81f1600-ec27-11e9-89a6-4cc2b1a3bce8.png)

The game also seems to use some sort of anti-aliasing in the SW renderer and on real hardware. This isn't emulated in the OGL renderer and there isn't any other form of AA implemented yet so I guess that may also be worth mentioning while I'm here.

Edit: This bug also seems to affect the behavior of the screen transitions when moving between areas.

**Comment by Arisotura** [comment]
seems to be something like missing clear bitmap? although it'd be overkill if they used that feature for this.

also: AA is only implemented in the software renderer, which emulates DS-style edge smoothing (pseudo-AA). OpenGL, being unable to emulate something that specific, will use regular AA techniques, but once I get there.

**Comment by McJ0n** [comment]
You probably don't need anymore information from me but I made a gif of the broken area transition effect (the incorrect/OGL behavior is the one where the screen turns black instead of orange).

![transition](https://user-images.githubusercontent.com/56448084/66883134-ca53c380-ef9a-11e9-8fd0-e2394e963b6d.gif)

**Comment by Arisotura** [comment]
ok what. the intro screen actually has a complete 3D scene rendered behind the white background. what's the point if you can't see it? weird.

haven't yet figured out what the bug is, just pointing out that amusing detail.

**Comment by Arisotura** [comment]
this seems to be related to some screen overlays that use 'equal' depth test, which isn't implemented yet in the GL renderer (it's tricky, the DS version of that has built-in error margins that need to be emulated)

**Comment by McJ0n** [comment]
> ok what. the intro screen actually has a complete 3D scene rendered behind the white background. what's the point if you can't see it? weird.

It's not used for the little cutscenes they show when you stay on the title screen long enough?

**Comment by Arisotura** [comment]
the scene may be visible later, haven't checked, but, well, why render it when it's not going to be visible?

**Comment by benderscruffy** [comment]
this can be closed
has been fixed
