### ISSUE TITLE
Local wifi, there must be dummy packets

### ISSUE THREAD

**Issue by ElatedEatrs** [melonDS-emu/melonDS#530]
I have an idea for local wifi, dummy packets+packet array
Basically every frame you use an array of the previous frame's packets to call from in case a packet didn't make it if one does make it you overwrite a packet,
Also give the frame limiter something to do by calling for packets then. I know the ds can't successfully send a packet every 4milisecond and still keep a connection with someone across the room. Also why not reload a savestates until the proper packet is received?

**Comment by Arisotura** [comment]
we can't just reuse old packets like that, it would be a major shitshow with things like Pictochat

also, a solution simpler than reloading savestates is to simply block emulation until a packet is received, but that will impact speed, and is not the correct solution to this problem.

I have an idea that should be better, I just need to actually implement it, someday
