### ISSUE TITLE
White screen after starting a game

### ISSUE THREAD

**Issue by Inky1003** [melonDS-emu/melonDS#569]
bios and firmware.zip (removed by @RSDuck)
There are my bios and firmware files.
I just start any game and then there is only white screen.

**Comment by RSDuck** [comment]
please don't upload copyrighted files, you're bringing us all into trouble

**Comment by RSDuck** [comment]
you can compare the checksum of your bios files with those found here: https://drastic-ds.com/viewtopic.php?t=5417

**Comment by Inky1003** [comment]
oh sorry I didn't knew. Also, they're DSi bios, should they be different?

**Comment by nathanielcwm** [comment]
Pretty sure you need to use files from the DS instead.

**Comment by benderscruffy** [comment]
can be closed
has been fixed

**Comment by Inky1003** [comment]
I'm closing, as this issue is quite old and must be reviewed.
