### ISSUE TITLE
Computer is 32 bit, still want a quality DS emulator

### ISSUE THREAD

**Issue by VoxNiphili** [melonDS-emu/melonDS#738]
Unfortunately, not everyone, like myself, has the capability of obtaining, and using, a 64 bit computer.

I am hoping you can release a version for those less fortunate, like myself, who have to use a 32 bit computer.

Thank thee kindly.

**Comment by RSDuck** [comment]
melonDS likely compiles and works as a 32-bit application. The thing is if your computer really only supports 32 bit x86 it probably too slow for melonDS and the JIT recompiler which could help in this regard only supports x64. Please check whether you aren't just running a 32-bit operating system with a 64-bit capable processor.

**Comment by MojoJojoDojo** [comment]
Well Desmume got some quality to it too lol or if you have a phone just use drastic.

**Comment by Zettymaster** [comment]
what CPU are you using that is 32bit only? (im not meaning that in a bad way, im more curious)
but as RSDuck said, emulating is not a very lightweight task and the DS is not a particularly easy thing to emulate anyway.

**Comment by nathanielcwm** [comment]
The last x86 cpus without AMD64 seem to be Athlon XPs and low end Pentium 4s. What CPU do you actually have?

**Comment by fancythedeveloper** [comment]
Either an old computer or a super low end new one.

**Comment by nathanielcwm** [comment]
@fancythedeveloper ok using arks filtering tool the last cpu without 64 bit was from 2014 and wikipedia states that their actual purpose is for smartwatches / other iot devices

It's also used in this arduino:
https://store.arduino.cc/usa/arduino-101

The last actual intel desktop cpu without 64 bit are the Intel Atom Lincroft cpus from 2010-2011

**Comment by nathanielcwm** [comment]
@VoxNiphili it would be really helpful if you actually came back to answer our questions.

**Comment by DanielTampeCaamano** [comment]
im interested in this, i have a tablet with 1gb ram so it cant run 32bit windows. it has a x64 procesor so performance shouldnt be droping too much. this is for testing as id like to test this with my other pc.

**Comment by CasualPokePlayer** [comment]
You *can't* run 32 bit Windows? Then why would you want a 32 bit version of the program then? That will be worse than a 64 bit version of the program (and again, if the program is 32 bits it will not have access to the JIT, you will be stuck with the interpreter and that will be made worse due to being forced into 32 bit compatibility mode).

**Comment by patataofcourse** [comment]
i think this is something that has been discussed over and over; you can compile melonDS as 32 bit if you really want, the instructions are in the readme. it's just not worth it considering how little power a PC that doesn't support 64 bit will have. if your PC supports 64 bit and you choose to keep using 32 bit, that's honestly just on you, and you're on your own

i think this should be closed
