### ISSUE TITLE
Improved polygon splitting break graphics?

### ISSUE THREAD

**Issue by mrcmunir** [melonDS-emu/melonDS#759]
Hello I detected some diferences when enable spliting polygon on Dragon Ball origins on nvidia jetson board with tegra GPU.

Opengl + improved polygon splitting enabled 
![Screenshot from 2020-09-15 11-23-17](https://user-images.githubusercontent.com/1274014/93193873-b59e2380-f747-11ea-8414-7818d719ee28.png)

Opengl without improved polygon splitting enabled  ok.
![Screenshot from 2020-09-15 11-34-07](https://user-images.githubusercontent.com/1274014/93194284-35c48900-f748-11ea-9548-1399f990a7d7.png)

Software rendering ok.
![Screenshot from 2020-09-15 11-24-46](https://user-images.githubusercontent.com/1274014/93194044-eda56680-f747-11ea-807f-37eaab42f1ef.png)

**Comment by Pik-a-boo** [comment]
Yeah it does break some games but thats why you can disable/enable it at will.

**Comment by mrcmunir** [comment]
I will closed seems it's fixed and can't reproduced in the current stage .
