### ISSUE TITLE
Local Multiplayer crashes

### ISSUE THREAD

**Issue by Redn2000** [melonDS-emu/melonDS#792]
Using either my own firmware or the very old dumps, my multiplayer windows fail to communicate after initial setup.
Currently using MelonDS 0.9 and I have npcap installed.

So far, no combination of wifi settings has allowed me to completely start multiplayer. The moment I get connected, for example with Kirby SSA, everything seems to work well for a minute. Though after that minute is up, the connection crashes either on the player 2 window, or on both if they try to transmit data. I've tried just doing direct mode with/without randomize MAC addresses but to no avail.

**Comment by RSDuck** [comment]
pcap and direct mode are completely irrelevant for local multiplayer.

It's a known issue that local wireless emulation is unstable. Try disabling the frame limiter and audio sync, besides there's not really any much to be done currently.

**Comment by Redn2000** [comment]
> 
> 
> pcap and direct mode are completely irrelevant for local multiplayer.

I understand that, I was just putting it out there that it would fail even over LAN or just not work.
 
> It's a known issue that local wireless emulation is unstable. Try disabling the frame limiter and audio sync, besides there's not really any much to be done currently.

Disabling on one instance seemed to do the trick.
So for the time being, the workaround I found was having the P1 window have only Audio Sync turned on, and the P2 window having neither on. Once connected it was able to work and P2 stopped going a mile a minute. 

And as a feature request, would it be possible to put in an option to manually change the framerate under video settings?

**Comment by JackoboLeChocobo** [comment]
@RSDuck : 
```
pcap and direct mode are completely irrelevant for local multiplayer.

It's a known issue that local wireless emulation is unstable.
Try disabling the frame limiter and audio sync, besides there's not really any
much to be done currently.
```

Question : For multiplayer local, do we need to create a server that runs DWC Network Server project ? https://github.com/barronwaffles/dwc_network_server_emulator

**Comment by RSDuck** [comment]
online multiplayer (as in wfc) as in opposed to local wireless works great, though the game you want to play needs to support it of course.

**Comment by KostaSaizo7** [comment]
For what is worth both Kirby Squeak Squad and Kirby Super Star Ultra (not sure which one the OP means) work fine in multiplayer with 2 instances on the same pc. Fixed by https://github.com/melonDS-emu/melonDS/pull/1516

![unknown (7)](https://user-images.githubusercontent.com/39852873/192101660-edeb8bab-6cfc-4675-918c-69738dd99fd3.png)
