### ISSUE TITLE
Soma Bringer Local Multiplayer Disconnecting

### ISSUE THREAD

**Issue by Schtolteheim** [melonDS-emu/melonDS#808]
Expected behavior: Connection sustained over adhoc between two local instances.
Observed behavior: Connection is briefly established, then lost.

Soma Bringer's adhoc menu displays room information properly and allows me to connect two instances, but they lose connection almost immediately. If I had to guess, it's some 1ms deadline thing.

https://www.youtube.com/watch?v=dAmsEC2e4ZE

Tested on unpatched JP ROM (CRC-32 E5907146). Identical result from fan translation-patched ROM (CRC-32 F63CC5C4). I used MelonDS v0.9, have yet to test previous versions for regression.

**Comment by RSDuck** [comment]
> Tested on unpatched JP ROM (CRC-32 E5907146). Identical result from fan translation-patched ROM (CRC-32 F63CC5C4). I used MelonDS v0.9, have yet to test previous versions for regression.

that's not necessary, local wireless emulation is known to be unstable. Try disabling the frame limiter that can alleviate the problem.

**Comment by KostaSaizo7** [comment]
Fixed by https://github.com/melonDS-emu/melonDS/pull/1516

![soma bringer](https://user-images.githubusercontent.com/39852873/192103659-e0ac6e4c-84ba-49fb-a61e-3bc2f78f67aa.jpg)
