### ISSUE TITLE
Wireless communication, i.e. Pictochat, over wlan (instead of theoretical radio p2p).

### ISSUE THREAD

**Issue by obso1337** [melonDS-emu/melonDS#82]
Instead of having the emulators need to be intra machine, would it be possible to add an option for communication over wlan, this would make not only pictochat a quite functional thing, but also multiplayer would be much better, intra-network of course.

**Comment by lordofharry** [comment]
Then this would allow people to vpn and actually play with others around the world, would be also quite fun.

**Comment by Nadia-h** [comment]
You should already  maybe be able to do this between computers on the same network, though nobody has tried it and it probably won't work very well.

**Comment by lordofharry** [comment]
I already tried doing it and it only works on the same machine itself, not just on same network.

**Comment by Arisotura** [comment]
making local multiplayer work over LAN isn't going to be feasible due to how tight the timings are. instead, we'll go for netplay.
