### ISSUE TITLE
[Regression] Mario vs. Luigi Is Broken in MelonDS 0.9

### ISSUE THREAD

**Issue by poudink** [melonDS-emu/melonDS#833]
I tried playing a game of New Super Mario Bros. Mario vs. Luigi in MelonDS (which used to work just fine), and found out that it simply didn't work. No matter how many times I tried, I can't get in-game. I always get a communication error first. I redownloaded MelonDS 0.8.3 just to test if it worked there and yep, it did. This means that something broke it between MelonDS 0.8.3 and MelonDS 0.9.

**Comment by poudink** [comment]
Okay, got the two instances of MelonDS to see eachother by enabling MAC Randomization, but the moment I tried starting a game, it immediatly got a connection error.

**Comment by Arisotura** [comment]
I guess you need to enable MAC randomization, in the wifi settings.

**Comment by poudink** [comment]
I already did that.

**Comment by RSDuck** [comment]
I just tried it, it works fine (except for the fact that it's running far too fast).

**Comment by poudink** [comment]
https://www.youtube.com/watch?v=cYitkd8aYzY
This happens every time for me. Sometimes it takes a bit longer but I'm never able to get in-game.

**Comment by poudink** [comment]
Came up with the theory that it might be due to a higher gap in framerate between the in focus and out of focus instances of melonDS between the two versions. Here's a video of 0.8.3 MvsL on my computer for comparison. https://www.youtube.com/watch?v=2TqU_ZtU-hg

**Comment by PimDoos** [comment]
The behaviour Poudink is also what I'm observing. Takes about a minute after starting the session, then the connection interrupts.
When starting the game over DS Download play, it doesn't get through the download phase before the connection is interrupted.

**Comment by KostaSaizo7** [comment]
Fixed by https://github.com/melonDS-emu/melonDS/pull/1516

![Screenshot 2022-09-24 085908](https://user-images.githubusercontent.com/39852873/192082586-af2c5d43-5e6c-453d-9699-0c3cfb2d6bf0.jpg)
![Screenshot 2022-09-24 085938](https://user-images.githubusercontent.com/39852873/192082594-2e0292ba-5a8d-40c0-b60d-b3aa47c78fef.jpg)
