### ISSUE TITLE
Turning in place on the stairs in the Luigi's Mansion stage of Mario Kart DS (USA) should crash the game but doesn't

### ISSUE THREAD

**Issue by ghost** [melonDS-emu/melonDS#908]
On real hardware stopping in place and pressing A + B to drift in place crashes the game. In MelonDS it doesn't for some reason. Here's a more detailed explanation and demonstration of the crash.

https://youtu.be/8kpaIrfYqw4?t=234

**Comment by RSDuck** [comment]
this is probably because we don't have a proper PU emulation

**Comment by poudink** [comment]
duplicate of https://github.com/Arisotura/melonDS/issues/96

**Comment by Tiberius1437** [comment]
My report is more coherent and provides actual evidence. Close the other one.

**Comment by WaluigiWare64** [comment]
Well the other issue was first, and this one is a duplicate.
This issue is the one that should be closed, as this one already has been reported.

**Comment by Tiberius1437** [comment]
Or just fix it and close both of them.
