### ISSUE TITLE
[REQUEST] Better WiFi connection

### ISSUE THREAD

**Issue by Erdu-EC** [melonDS-emu/melonDS#921]
I have tried to play pokemon platinum in multiplayer, but when fighting another pc, the connection is lost when launching the second attack or sometimes even before.

I would like you to please improve the Wi-Fi connection system, I really think it is an excellent feature and it really makes the emulator different from the rest.

It is an excellent emulator, I never thought that I could have a Pokemon DS game with my brother, but thanks to you I see that dream very close.

I hope you take my humble opinion into account.

Note: I am a programmer, I would be very grateful if you shared documentation about the console's Wi-Fi system, I am very interested in how it works.

Note 2: Success in all your projects!

**Comment by RSDuck** [comment]
wifi or local wireless? Wifi should be pretty stable.

**Comment by Erdu-EC** [comment]
Thanks for answer so soon.

I could not say, I think it is a local connection.  Since it is a duel between only two players.  Although I wouldn't bet on it.

**Comment by RSDuck** [comment]
it says in the game. Local wireless is if you connect two DS systems directly (so you would need to be next to each other), while wifi uses the now defunct but replaceable WFC to connect players over the internet.

**Comment by Erdu-EC** [comment]
If I understand the difference of the two modes, after all networks and communications are my trade, programming is my hobby and complement.
I consider it to be a local connection between the two consoles since the game asks which one will be the leader and which one will join the access point.

**Comment by RianCaio** [comment]
So yes its local multiplayer
