### ISSUE TITLE
[Feature Request] Rumble Pak Support

### ISSUE THREAD

**Issue by puigru** [melonDS-emu/melonDS#99]
[Some games](http://nintendo.wikia.com/wiki/List_of_Nintendo_DS_games_with_Rumble_Pak_support) support the use of the [Rumble Pak](http://squallsnake.com/wp-content/uploads/2012/08/DS-Rumble-Pak.jpg), a Slot-2 cartridge that provides haptic feedback.

An example its use can be seen during [a short cinematic](https://youtu.be/OI2T744kCHw?t=3m8s) in the tutorial of Mario & Luigi: Partners in Time (~3 minutes into the game).

**Comment by Buenia0** [comment]
Is anyone still working on this issue? Because I'm currently working on a custom fork of melonDS with support for this addon...

**Comment by RSDuck** [comment]
please make a pull request once you feel it's ready so we can review it for merging

**Comment by Buenia0** [comment]
Okay, I will!

**Comment by Buenia0** [comment]
Just got to fix some minor formatting issues, and my fork will be ready to merge!

**Comment by Priception** [comment]
Is this feature added in the end?

As i'm trying to find it and the only addon option is the "Memory Expansion"

**Comment by patataofcourse** [comment]
not as far as im aware, currently dev efforts are focused on netplay and the compute shader renderer afaik

**Comment by asiekierka** [comment]
Resolved by https://github.com/melonDS-emu/melonDS/pull/2101
